/**
 *27-Nov-2019
 *OpRoute_DaoImp.java
 * TODO
 *com.st.frpobcc.dao
 *OpRoute_DaoImp.java
 *Roshan Lal Tailor
 */
package com.st.frpobcc.dao;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import javax.sql.DataSource;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.stereotype.Repository;

import com.st.common.DatabaseUtil;
import com.st.frpobcc.model.OpRoute_2;

/**
 * @author sohan
 *
 */
@Repository
public class OpRoute_2DaoImp implements OpRoute_2Dao {
	
	@Autowired
	@Qualifier("dataSourceOBCC")
	private DataSource dataSourceQRT;
	/* (non-Javadoc)
	 * @see com.st.frpobcc.dao.OpRoute_1Dao#saveorUpdate(com.st.frpobcc.model.OpRoute_1)
	 */
	@Override
	public void saveorUpdate(OpRoute_2 data) {
		NamedParameterJdbcTemplate jdbcTemplate = new NamedParameterJdbcTemplate(dataSourceQRT);
	 	MapSqlParameterSource paramSource=new MapSqlParameterSource();
		
		paramSource.addValue("position",data.getPosition());
		paramSource.addValue("operatorName",data.getOperatorname());
		paramSource.addValue("date",data.getDate());
		paramSource.addValue("crew",data.getCrew());
		paramSource.addValue("shift",data.getShift());
		paramSource.addValue("machinedown",data.isMachinedown());
		
		paramSource.addValue("comments",data.getComments());
		paramSource.addValue("cmt9amarea", data.getCmt9amarea());
		paramSource.addValue("cmt1pmarea", data.getCmt1pmarea());
		paramSource.addValue("cmt5pmarea", data.getCmt5pmarea());
		paramSource.addValue("cmt9pmarea", data.getCmt9pmarea());
		paramSource.addValue("cmt1amarea", data.getCmt1amarea());
		paramSource.addValue("cmt5amarea", data.getCmt5amarea());
		paramSource.addValue("ok",data.getOk());
		paramSource.addValue("button1pm",data.getButton1pm());
		paramSource.addValue("button5pm",data.getButton5pm());
		paramSource.addValue("button9pm",data.getButton9pm());
		paramSource.addValue("button1am",data.getButton1am());
		paramSource.addValue("button5am",data.getButton5am());	
		paramSource.addValue("techniciansinitials_freq",data.getTechniciansinitials_freq());
		paramSource.addValue("techniciansinitials_9am",data.getTechniciansinitials_9am());	
		paramSource.addValue("techniciansinitials_1pm",data.getTechniciansinitials_1pm());	
		paramSource.addValue("techniciansinitials_5pm",data.getTechniciansinitials_5pm());	
		paramSource.addValue("techniciansinitials_9pm",data.getTechniciansinitials_9pm());	
		paramSource.addValue("techniciansinitials_1am",data.getTechniciansinitials_1am());	
		paramSource.addValue("techniciansinitials_5am",data.getTechniciansinitials_5am());
		paramSource.addValue("techniciansinitials_51am",data.getTechniciansinitials_51am());
		paramSource.addValue("tertiarypress1_1_freq",data.getTertiarypress1_1_freq());
		paramSource.addValue("tertiarypress1_1_8am",data.getTertiarypress1_1_8am());
		paramSource.addValue("tertiarypress1_1_12pm",data.getTertiarypress1_1_12pm());
		paramSource.addValue("tertiarypress1_1_4pm",data.getTertiarypress1_1_4pm());
		paramSource.addValue("tertiarypress1_1_8pm",data.getTertiarypress1_1_8pm());
		paramSource.addValue("tertiarypress1_1_12am",data.getTertiarypress1_1_12am());
		paramSource.addValue("tertiarypress1_1_4am",data.getTertiarypress1_1_4am());
		paramSource.addValue("tertiarypress1_1_parameters",data.getTertiarypress1_1_parameters());
		paramSource.addValue("tertiarypress1_2_freq",data.getTertiarypress1_2_freq());
		paramSource.addValue("tertiarypress1_2_8am",data.getTertiarypress1_2_8am());
		paramSource.addValue("tertiarypress1_2_12pm",data.getTertiarypress1_2_12pm());
		paramSource.addValue("tertiarypress1_2_4pm",data.getTertiarypress1_2_4pm());
		paramSource.addValue("tertiarypress1_2_8pm",data.getTertiarypress1_2_8pm());
		paramSource.addValue("tertiarypress1_2_12am",data.getTertiarypress1_2_12am());
		paramSource.addValue("tertiarypress1_2_4am",data.getTertiarypress1_2_4am());
		paramSource.addValue("tertiarypress1_2_parameters",data.getTertiarypress1_2_parameters());
		paramSource.addValue("tertiarypress1_3_freq",data.getTertiarypress1_3_freq());
		paramSource.addValue("tertiarypress1_3_8am",data.getTertiarypress1_3_8am());
		paramSource.addValue("tertiarypress1_3_12pm",data.getTertiarypress1_3_12pm());
		paramSource.addValue("tertiarypress1_3_4pm",data.getTertiarypress1_3_4pm());
		paramSource.addValue("tertiarypress1_3_8pm",data.getTertiarypress1_3_8pm());
		paramSource.addValue("tertiarypress1_3_12am",data.getTertiarypress1_3_12am());
		paramSource.addValue("tertiarypress1_3_4am",data.getTertiarypress1_3_4am());
		paramSource.addValue("tertiarypress1_3_parameters",data.getTertiarypress1_3_parameters());
		paramSource.addValue("tertiarypress1_4_freq",data.getTertiarypress1_4_freq());
		paramSource.addValue("tertiarypress1_4_8am",data.getTertiarypress1_4_8am());
		paramSource.addValue("tertiarypress1_4_12pm",data.getTertiarypress1_4_12pm());
		paramSource.addValue("tertiarypress1_4_4pm",data.getTertiarypress1_4_4pm());
		paramSource.addValue("tertiarypress1_4_8pm",data.getTertiarypress1_4_8pm());
		paramSource.addValue("tertiarypress1_4_12am",data.getTertiarypress1_4_12am());
		paramSource.addValue("tertiarypress1_4_4am",data.getTertiarypress1_4_4am());
		paramSource.addValue("tertiarypress1_4_parameters",data.getTertiarypress1_4_parameters());
		paramSource.addValue("tertiarypress1_5_freq",data.getTertiarypress1_5_freq());
		paramSource.addValue("tertiarypress1_5_8am",data.getTertiarypress1_5_8am());
		paramSource.addValue("tertiarypress1_5_12pm",data.getTertiarypress1_5_12pm());
		paramSource.addValue("tertiarypress1_5_4pm",data.getTertiarypress1_5_4pm());
		paramSource.addValue("tertiarypress1_5_8pm",data.getTertiarypress1_5_8pm());
		paramSource.addValue("tertiarypress1_5_12am",data.getTertiarypress1_5_12am());
		paramSource.addValue("tertiarypress1_5_4am",data.getTertiarypress1_5_4am());
		paramSource.addValue("tertiarypress1_5_parameters",data.getTertiarypress1_5_parameters());
		paramSource.addValue("tertiarypress1_6_freq",data.getTertiarypress1_6_freq());
		paramSource.addValue("tertiarypress1_6_8am",data.getTertiarypress1_6_8am());
		paramSource.addValue("tertiarypress1_6_12pm",data.getTertiarypress1_6_12pm());
		paramSource.addValue("tertiarypress1_6_4pm",data.getTertiarypress1_6_4pm());
		paramSource.addValue("tertiarypress1_6_8pm",data.getTertiarypress1_6_8pm());
		paramSource.addValue("tertiarypress1_6_12am",data.getTertiarypress1_6_12am());
		paramSource.addValue("tertiarypress1_6_4am",data.getTertiarypress1_6_4am());
		paramSource.addValue("tertiarypress1_6_parameters",data.getTertiarypress1_6_parameters());
		paramSource.addValue("tertiarypress1_7_freq",data.getTertiarypress1_7_freq());
		paramSource.addValue("tertiarypress1_7_8am",data.getTertiarypress1_7_8am());
		paramSource.addValue("tertiarypress1_7_12pm",data.getTertiarypress1_7_12pm());
		paramSource.addValue("tertiarypress1_7_4pm",data.getTertiarypress1_7_4pm());
		paramSource.addValue("tertiarypress1_7_8pm",data.getTertiarypress1_7_8pm());
		paramSource.addValue("tertiarypress1_7_12am",data.getTertiarypress1_7_12am());
		paramSource.addValue("tertiarypress1_7_4am",data.getTertiarypress1_7_4am());
		paramSource.addValue("tertiarypress1_7_parameters",data.getTertiarypress1_7_parameters());
		paramSource.addValue("tertiarypress1_8_freq",data.getTertiarypress1_8_freq());
		paramSource.addValue("tertiarypress1_8_8am",data.getTertiarypress1_8_8am());
		paramSource.addValue("tertiarypress1_8_12pm",data.getTertiarypress1_8_12pm());
		paramSource.addValue("tertiarypress1_8_4pm",data.getTertiarypress1_8_4pm());
		paramSource.addValue("tertiarypress1_8_8pm",data.getTertiarypress1_8_8pm());
		paramSource.addValue("tertiarypress1_8_12am",data.getTertiarypress1_8_12am());
		paramSource.addValue("tertiarypress1_8_4am",data.getTertiarypress1_8_4am());
		paramSource.addValue("tertiarypress1_8_parameters",data.getTertiarypress1_8_parameters());		
		paramSource.addValue("tertiarypress1_9_freq",data.getTertiarypress1_9_freq());
		paramSource.addValue("tertiarypress1_9_8am",data.getTertiarypress1_9_8am());
		paramSource.addValue("tertiarypress1_9_12pm",data.getTertiarypress1_9_12pm());
		paramSource.addValue("tertiarypress1_9_4pm",data.getTertiarypress1_9_4pm());
		paramSource.addValue("tertiarypress1_9_8pm",data.getTertiarypress1_9_8pm());
		paramSource.addValue("tertiarypress1_9_12am",data.getTertiarypress1_9_12am());
		paramSource.addValue("tertiarypress1_9_4am",data.getTertiarypress1_9_4am());
		paramSource.addValue("tertiarypress1_9_parameters",data.getTertiarypress1_9_parameters());		
		paramSource.addValue("tertiarypress1_10_freq",data.getTertiarypress1_10_freq());
		paramSource.addValue("tertiarypress1_10_8am",data.getTertiarypress1_10_8am());
		paramSource.addValue("tertiarypress1_10_12pm",data.getTertiarypress1_10_12pm());
		paramSource.addValue("tertiarypress1_10_4pm",data.getTertiarypress1_10_4pm());
		paramSource.addValue("tertiarypress1_10_8pm",data.getTertiarypress1_10_8pm());
		paramSource.addValue("tertiarypress1_10_12am",data.getTertiarypress1_10_12am());
		paramSource.addValue("tertiarypress1_10_4am",data.getTertiarypress1_10_4am());
		paramSource.addValue("tertiarypress1_10_parameters",data.getTertiarypress1_10_parameters());
		paramSource.addValue("tertiarypress1_11_freq",data.getTertiarypress1_11_freq());
		paramSource.addValue("tertiarypress1_11_8am",data.getTertiarypress1_11_8am());
		paramSource.addValue("tertiarypress1_11_12pm",data.getTertiarypress1_11_12pm());
		paramSource.addValue("tertiarypress1_11_4pm",data.getTertiarypress1_11_4pm());
		paramSource.addValue("tertiarypress1_11_8pm",data.getTertiarypress1_11_8pm());
		paramSource.addValue("tertiarypress1_11_12am",data.getTertiarypress1_11_12am());
		paramSource.addValue("tertiarypress1_11_4am",data.getTertiarypress1_11_4am());
		paramSource.addValue("tertiarypress1_11_parameters",data.getTertiarypress1_11_parameters());
		paramSource.addValue("tertiarypress1_12_freq",data.getTertiarypress1_12_freq());
		paramSource.addValue("tertiarypress1_12_8am",data.getTertiarypress1_12_8am());
		paramSource.addValue("tertiarypress1_12_12pm",data.getTertiarypress1_12_12pm());
		paramSource.addValue("tertiarypress1_12_4pm",data.getTertiarypress1_12_4pm());
		paramSource.addValue("tertiarypress1_12_8pm",data.getTertiarypress1_12_8pm());
		paramSource.addValue("tertiarypress1_12_12am",data.getTertiarypress1_12_12am());
		paramSource.addValue("tertiarypress1_12_4am",data.getTertiarypress1_12_4am());
		paramSource.addValue("tertiarypress1_12_parameters",data.getTertiarypress1_12_parameters());
		paramSource.addValue("tertiarypress1_13_freq",data.getTertiarypress1_13_freq());
		paramSource.addValue("tertiarypress1_13_8am",data.getTertiarypress1_13_8am());
		paramSource.addValue("tertiarypress1_13_12pm",data.getTertiarypress1_13_12pm());
		paramSource.addValue("tertiarypress1_13_4pm",data.getTertiarypress1_13_4pm());
		paramSource.addValue("tertiarypress1_13_8pm",data.getTertiarypress1_13_8pm());
		paramSource.addValue("tertiarypress1_13_12am",data.getTertiarypress1_13_12am());
		paramSource.addValue("tertiarypress1_13_4am",data.getTertiarypress1_13_4am());
		paramSource.addValue("tertiarypress1_13_parameters",data.getTertiarypress1_13_parameters());
		paramSource.addValue("tertiarypress1_14_freq",data.getTertiarypress1_14_freq());
		paramSource.addValue("tertiarypress1_14_8am",data.getTertiarypress1_14_8am());
		paramSource.addValue("tertiarypress1_14_12pm",data.getTertiarypress1_14_12pm());
		paramSource.addValue("tertiarypress1_14_4pm",data.getTertiarypress1_14_4pm());
		paramSource.addValue("tertiarypress1_14_8pm",data.getTertiarypress1_14_8pm());
		paramSource.addValue("tertiarypress1_14_12am",data.getTertiarypress1_14_12am());
		paramSource.addValue("tertiarypress1_14_4am",data.getTertiarypress1_14_4am());
		paramSource.addValue("tertiarypress1_14_parameters",data.getTertiarypress1_14_parameters());
		paramSource.addValue("tertiarypress2_1_freq",data.getTertiarypress2_1_freq());
		paramSource.addValue("tertiarypress2_1_8am",data.getTertiarypress2_1_8am());
		paramSource.addValue("tertiarypress2_1_12pm",data.getTertiarypress2_1_12pm());
		paramSource.addValue("tertiarypress2_1_4pm",data.getTertiarypress2_1_4pm());
		paramSource.addValue("tertiarypress2_1_8pm",data.getTertiarypress2_1_8pm());
		paramSource.addValue("tertiarypress2_1_12am",data.getTertiarypress2_1_12am());
		paramSource.addValue("tertiarypress2_1_4am",data.getTertiarypress2_1_4am());
		paramSource.addValue("tertiarypress2_1_parameters",data.getTertiarypress2_1_parameters());
		paramSource.addValue("tertiarypress2_2_freq",data.getTertiarypress2_2_freq());
		paramSource.addValue("tertiarypress2_2_8am",data.getTertiarypress2_2_8am());
		paramSource.addValue("tertiarypress2_2_12pm",data.getTertiarypress2_2_12pm());
		paramSource.addValue("tertiarypress2_2_4pm",data.getTertiarypress2_2_4pm());
		paramSource.addValue("tertiarypress2_2_8pm",data.getTertiarypress2_2_8pm());
		paramSource.addValue("tertiarypress2_2_12am",data.getTertiarypress2_2_12am());
		paramSource.addValue("tertiarypress2_2_4am",data.getTertiarypress2_2_4am());
		paramSource.addValue("tertiarypress2_2_parameters",data.getTertiarypress2_2_parameters());
		paramSource.addValue("tertiarypress2_3_freq",data.getTertiarypress2_3_freq());
		paramSource.addValue("tertiarypress2_3_8am",data.getTertiarypress2_3_8am());
		paramSource.addValue("tertiarypress2_3_12pm",data.getTertiarypress2_3_12pm());
		paramSource.addValue("tertiarypress2_3_4pm",data.getTertiarypress2_3_4pm());
		paramSource.addValue("tertiarypress2_3_8pm",data.getTertiarypress2_3_8pm());
		paramSource.addValue("tertiarypress2_3_12am",data.getTertiarypress2_3_12am());
		paramSource.addValue("tertiarypress2_3_4am",data.getTertiarypress2_3_4am());
		paramSource.addValue("tertiarypress2_3_parameters",data.getTertiarypress2_3_parameters());
		paramSource.addValue("tertiarypress2_4_freq",data.getTertiarypress2_4_freq());
		paramSource.addValue("tertiarypress2_4_8am",data.getTertiarypress2_4_8am());
		paramSource.addValue("tertiarypress2_4_12pm",data.getTertiarypress2_4_12pm());
		paramSource.addValue("tertiarypress2_4_4pm",data.getTertiarypress2_4_4pm());
		paramSource.addValue("tertiarypress2_4_8pm",data.getTertiarypress2_4_8pm());
		paramSource.addValue("tertiarypress2_4_12am",data.getTertiarypress2_4_12am());
		paramSource.addValue("tertiarypress2_4_4am",data.getTertiarypress2_4_4am());
		paramSource.addValue("tertiarypress2_4_parameters",data.getTertiarypress2_4_parameters());
		paramSource.addValue("tertiarypress2_5_freq",data.getTertiarypress2_5_freq());
		paramSource.addValue("tertiarypress2_5_8am",data.getTertiarypress2_5_8am());
		paramSource.addValue("tertiarypress2_5_12pm",data.getTertiarypress2_5_12pm());
		paramSource.addValue("tertiarypress2_5_4pm",data.getTertiarypress2_5_4pm());
		paramSource.addValue("tertiarypress2_5_8pm",data.getTertiarypress2_5_8pm());
		paramSource.addValue("tertiarypress2_5_12am",data.getTertiarypress2_5_12am());
		paramSource.addValue("tertiarypress2_5_4am",data.getTertiarypress2_5_4am());
		paramSource.addValue("tertiarypress2_5_parameters",data.getTertiarypress2_5_parameters());
		paramSource.addValue("tertiarypress2_6_freq",data.getTertiarypress2_6_freq());
		paramSource.addValue("tertiarypress2_6_8am",data.getTertiarypress2_6_8am());
		paramSource.addValue("tertiarypress2_6_12pm",data.getTertiarypress2_6_12pm());
		paramSource.addValue("tertiarypress2_6_4pm",data.getTertiarypress2_6_4pm());
		paramSource.addValue("tertiarypress2_6_8pm",data.getTertiarypress2_6_8pm());
		paramSource.addValue("tertiarypress2_6_12am",data.getTertiarypress2_6_12am());
		paramSource.addValue("tertiarypress2_6_4am",data.getTertiarypress2_6_4am());
		paramSource.addValue("tertiarypress2_6_parameters",data.getTertiarypress2_6_parameters());
		paramSource.addValue("tertiarypress2_7_freq",data.getTertiarypress2_7_freq());
		paramSource.addValue("tertiarypress2_7_8am",data.getTertiarypress2_7_8am());
		paramSource.addValue("tertiarypress2_7_12pm",data.getTertiarypress2_7_12pm());
		paramSource.addValue("tertiarypress2_7_4pm",data.getTertiarypress2_7_4pm());
		paramSource.addValue("tertiarypress2_7_8pm",data.getTertiarypress2_7_8pm());
		paramSource.addValue("tertiarypress2_7_12am",data.getTertiarypress2_7_12am());
		paramSource.addValue("tertiarypress2_7_4am",data.getTertiarypress2_7_4am());
		paramSource.addValue("tertiarypress2_7_parameters",data.getTertiarypress2_7_parameters());
		paramSource.addValue("tertiarypress2_8_freq",data.getTertiarypress2_8_freq());
		paramSource.addValue("tertiarypress2_8_8am",data.getTertiarypress2_8_8am());
		paramSource.addValue("tertiarypress2_8_12pm",data.getTertiarypress2_8_12pm());
		paramSource.addValue("tertiarypress2_8_4pm",data.getTertiarypress2_8_4pm());
		paramSource.addValue("tertiarypress2_8_8pm",data.getTertiarypress2_8_8pm());
		paramSource.addValue("tertiarypress2_8_12am",data.getTertiarypress2_8_12am());
		paramSource.addValue("tertiarypress2_8_4am",data.getTertiarypress2_8_4am());
		paramSource.addValue("tertiarypress2_8_parameters",data.getTertiarypress2_8_parameters());		
		paramSource.addValue("tertiarypress2_9_freq",data.getTertiarypress2_9_freq());
		paramSource.addValue("tertiarypress2_9_8am",data.getTertiarypress2_9_8am());
		paramSource.addValue("tertiarypress2_9_12pm",data.getTertiarypress2_9_12pm());
		paramSource.addValue("tertiarypress2_9_4pm",data.getTertiarypress2_9_4pm());
		paramSource.addValue("tertiarypress2_9_8pm",data.getTertiarypress2_9_8pm());
		paramSource.addValue("tertiarypress2_9_12am",data.getTertiarypress2_9_12am());
		paramSource.addValue("tertiarypress2_9_4am",data.getTertiarypress2_9_4am());
		paramSource.addValue("tertiarypress2_9_parameters",data.getTertiarypress2_9_parameters());		
		paramSource.addValue("tertiarypress2_10_freq",data.getTertiarypress2_10_freq());
		paramSource.addValue("tertiarypress2_10_8am",data.getTertiarypress2_10_8am());
		paramSource.addValue("tertiarypress2_10_12pm",data.getTertiarypress2_10_12pm());
		paramSource.addValue("tertiarypress2_10_4pm",data.getTertiarypress2_10_4pm());
		paramSource.addValue("tertiarypress2_10_8pm",data.getTertiarypress2_10_8pm());
		paramSource.addValue("tertiarypress2_10_12am",data.getTertiarypress2_10_12am());
		paramSource.addValue("tertiarypress2_10_4am",data.getTertiarypress2_10_4am());
		paramSource.addValue("tertiarypress2_10_parameters",data.getTertiarypress2_10_parameters());
		paramSource.addValue("tertiarypress2_11_freq",data.getTertiarypress2_11_freq());
		paramSource.addValue("tertiarypress2_11_8am",data.getTertiarypress2_11_8am());
		paramSource.addValue("tertiarypress2_11_12pm",data.getTertiarypress2_11_12pm());
		paramSource.addValue("tertiarypress2_11_4pm",data.getTertiarypress2_11_4pm());
		paramSource.addValue("tertiarypress2_11_8pm",data.getTertiarypress2_11_8pm());
		paramSource.addValue("tertiarypress2_11_12am",data.getTertiarypress2_11_12am());
		paramSource.addValue("tertiarypress2_11_4am",data.getTertiarypress2_11_4am());
		paramSource.addValue("tertiarypress2_11_parameters",data.getTertiarypress2_11_parameters());
	
		paramSource.addValue("cutterlayboy_wetlap1_freq",data.getCutterlayboy_wetlap1_freq());
		paramSource.addValue("cutterlayboy_wetlap1_8am",data.getCutterlayboy_wetlap1_8am());
		paramSource.addValue("cutterlayboy_wetlap1_12pm",data.getCutterlayboy_wetlap1_12pm());
		paramSource.addValue("cutterlayboy_wetlap1_4pm",data.getCutterlayboy_wetlap1_4pm());
		paramSource.addValue("cutterlayboy_wetlap1_8pm",data.getCutterlayboy_wetlap1_8pm());
		paramSource.addValue("cutterlayboy_wetlap1_12am",data.getCutterlayboy_wetlap1_12am());
		paramSource.addValue("cutterlayboy_wetlap1_4am",data.getCutterlayboy_wetlap1_4am());
		paramSource.addValue("cutterlayboy_wetlap1_parameters",data.getCutterlayboy_wetlap1_parameters());
		paramSource.addValue("cutterlayboy_wetlap2_freq",data.getCutterlayboy_wetlap2_freq());
		paramSource.addValue("cutterlayboy_wetlap2_8am",data.getCutterlayboy_wetlap2_8am());
		paramSource.addValue("cutterlayboy_wetlap2_12pm",data.getCutterlayboy_wetlap2_12pm());
		paramSource.addValue("cutterlayboy_wetlap2_4pm",data.getCutterlayboy_wetlap2_4pm());
		paramSource.addValue("cutterlayboy_wetlap2_8pm",data.getCutterlayboy_wetlap2_8pm());
		paramSource.addValue("cutterlayboy_wetlap2_12am",data.getCutterlayboy_wetlap2_12am());
		paramSource.addValue("cutterlayboy_wetlap2_4am",data.getCutterlayboy_wetlap2_4am());
		paramSource.addValue("cutterlayboy_wetlap2_parameters",data.getCutterlayboy_wetlap2_parameters());
		paramSource.addValue("cutterlayboy_wetlap3_freq",data.getCutterlayboy_wetlap3_freq());
		paramSource.addValue("cutterlayboy_wetlap3_8am",data.getCutterlayboy_wetlap3_8am());
		paramSource.addValue("cutterlayboy_wetlap3_12pm",data.getCutterlayboy_wetlap3_12pm());
		paramSource.addValue("cutterlayboy_wetlap3_4pm",data.getCutterlayboy_wetlap3_4pm());
		paramSource.addValue("cutterlayboy_wetlap3_8pm",data.getCutterlayboy_wetlap3_8pm());
		paramSource.addValue("cutterlayboy_wetlap3_12am",data.getCutterlayboy_wetlap3_12am());
		paramSource.addValue("cutterlayboy_wetlap3_4am",data.getCutterlayboy_wetlap3_4am());
		paramSource.addValue("cutterlayboy_wetlap3_parameters",data.getCutterlayboy_wetlap3_parameters());
		paramSource.addValue("cutterlayboy_wetlap4_freq",data.getCutterlayboy_wetlap4_freq());
		paramSource.addValue("cutterlayboy_wetlap4_8am",data.getCutterlayboy_wetlap4_8am());
		paramSource.addValue("cutterlayboy_wetlap4_12pm",data.getCutterlayboy_wetlap4_12pm());
		paramSource.addValue("cutterlayboy_wetlap4_4pm",data.getCutterlayboy_wetlap4_4pm());
		paramSource.addValue("cutterlayboy_wetlap4_8pm",data.getCutterlayboy_wetlap4_8pm());
		paramSource.addValue("cutterlayboy_wetlap4_12am",data.getCutterlayboy_wetlap4_12am());
		paramSource.addValue("cutterlayboy_wetlap4_4am",data.getCutterlayboy_wetlap4_4am());
		paramSource.addValue("cutterlayboy_wetlap4_parameters",data.getCutterlayboy_wetlap4_parameters());
		paramSource.addValue("cutterlayboy_wetlap5_freq",data.getCutterlayboy_wetlap5_freq());
		paramSource.addValue("cutterlayboy_wetlap5_8am",data.getCutterlayboy_wetlap5_8am());
		paramSource.addValue("cutterlayboy_wetlap5_12pm",data.getCutterlayboy_wetlap5_12pm());
		paramSource.addValue("cutterlayboy_wetlap5_4pm",data.getCutterlayboy_wetlap5_4pm());
		paramSource.addValue("cutterlayboy_wetlap5_8pm",data.getCutterlayboy_wetlap5_8pm());
		paramSource.addValue("cutterlayboy_wetlap5_12am",data.getCutterlayboy_wetlap5_12am());
		paramSource.addValue("cutterlayboy_wetlap5_4am",data.getCutterlayboy_wetlap5_4am());
		paramSource.addValue("cutterlayboy_wetlap5_parameters",data.getCutterlayboy_wetlap5_parameters());
		paramSource.addValue("cutterlayboy_wetlap6_freq",data.getCutterlayboy_wetlap6_freq());
		paramSource.addValue("cutterlayboy_wetlap6_8am",data.getCutterlayboy_wetlap6_8am());
		paramSource.addValue("cutterlayboy_wetlap6_12pm",data.getCutterlayboy_wetlap6_12pm());
		paramSource.addValue("cutterlayboy_wetlap6_4pm",data.getCutterlayboy_wetlap6_4pm());
		paramSource.addValue("cutterlayboy_wetlap6_8pm",data.getCutterlayboy_wetlap6_8pm());
		paramSource.addValue("cutterlayboy_wetlap6_12am",data.getCutterlayboy_wetlap6_12am());
		paramSource.addValue("cutterlayboy_wetlap6_4am",data.getCutterlayboy_wetlap6_4am());
		paramSource.addValue("cutterlayboy_wetlap6_parameters",data.getCutterlayboy_wetlap6_parameters());
		paramSource.addValue("cutterlayboy_wetlap7_freq",data.getCutterlayboy_wetlap7_freq());
		paramSource.addValue("cutterlayboy_wetlap7_8am",data.getCutterlayboy_wetlap7_8am());
		paramSource.addValue("cutterlayboy_wetlap7_12pm",data.getCutterlayboy_wetlap7_12pm());
		paramSource.addValue("cutterlayboy_wetlap7_4pm",data.getCutterlayboy_wetlap7_4pm());
		paramSource.addValue("cutterlayboy_wetlap7_8pm",data.getCutterlayboy_wetlap7_8pm());
		paramSource.addValue("cutterlayboy_wetlap7_12am",data.getCutterlayboy_wetlap7_12am());
		paramSource.addValue("cutterlayboy_wetlap7_4am",data.getCutterlayboy_wetlap7_4am());
		paramSource.addValue("cutterlayboy_wetlap7_parameters",data.getCutterlayboy_wetlap7_parameters());
		paramSource.addValue("cmt9amarea", data.getCmt9amarea());
		paramSource.addValue("cmt1pmarea", data.getCmt1pmarea());
		paramSource.addValue("cmt5pmarea", data.getCmt5pmarea());
		paramSource.addValue("cmt9pmarea", data.getCmt9pmarea());
		paramSource.addValue("cmt1amarea", data.getCmt1amarea());
		paramSource.addValue("cmt5amarea", data.getCmt5amarea());
		
		if (data.getId() == 0) {	
			String sql=DatabaseUtil.getSQL("sql/insertOpRoute_2.sql");
			jdbcTemplate.update(sql, paramSource);
		}	
		else
		{
			paramSource.addValue("id",data.getId());
			String sql=DatabaseUtil.getSQL("sql/updateOpRoute_2.sql");
			jdbcTemplate.update(sql, paramSource);
		}
		
	}

	@Override
	public List<OpRoute_2> getData(String sdate,String edate) {
		
		JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSourceQRT);
		String sql = "select * from [OpRoute_2] where date BETWEEN ? AND ?";
		List<OpRoute_2> oproute_2=null;
		try {
			oproute_2 = jdbcTemplate.query(sql, new Object[] {sdate,edate}, new RowMapper<OpRoute_2>() {
						
						@Override
						public OpRoute_2 mapRow(ResultSet rs, int arg1) throws SQLException {
							OpRoute_2 data=new OpRoute_2();
							data.setId(rs.getInt("id"));
							data.setPosition(rs.getString("position"));
							data.setCrew(rs.getString("crew"));
							data.setDate(rs.getString("date"));
							data.setMachinedown(rs.getBoolean("machinedown"));
							data.setComments(rs.getString("comments"));
							data.setTechniciansinitials_freq(rs.getString("techniciansinitials_freq"));
							data.setTechniciansinitials_9am(rs.getString("techniciansinitials_9am"));
							data.setTechniciansinitials_1pm(rs.getString("techniciansinitials_1pm"));
							data.setTechniciansinitials_5pm(rs.getString("techniciansinitials_5pm"));
							data.setTechniciansinitials_9pm(rs.getString("techniciansinitials_9pm"));
							data.setTechniciansinitials_1am(rs.getString("techniciansinitials_1am"));
							data.setTechniciansinitials_5am(rs.getString("techniciansinitials_5am"));
							data.setTechniciansinitials_51am(rs.getString("techniciansinitials_51am"));
							data.setTertiarypress1_1_freq(rs.getString("tertiarypress1_1_freq"));
							data.setTertiarypress1_1_8am(rs.getString("tertiarypress1_1_8am"));
							data.setTertiarypress1_1_12pm(rs.getString("tertiarypress1_1_12pm"));
							data.setTertiarypress1_1_4pm(rs.getString("tertiarypress1_1_4pm"));
							data.setTertiarypress1_1_8pm(rs.getString("tertiarypress1_1_8pm"));
							data.setTertiarypress1_1_12am(rs.getString("tertiarypress1_1_12am"));
							data.setTertiarypress1_1_4am(rs.getString("tertiarypress1_1_4am"));
							data.setTertiarypress1_1_parameters(rs.getString("tertiarypress1_1_parameters"));
							data.setTertiarypress1_2_freq(rs.getString("tertiarypress1_2_freq"));
							data.setTertiarypress1_2_8am(rs.getString("tertiarypress1_2_8am"));
							data.setTertiarypress1_2_12pm(rs.getString("tertiarypress1_2_12pm"));
							data.setTertiarypress1_2_4pm(rs.getString("tertiarypress1_2_4pm"));
							data.setTertiarypress1_2_8pm(rs.getString("tertiarypress1_2_8pm"));
							data.setTertiarypress1_2_12am(rs.getString("tertiarypress1_2_12am"));
							data.setTertiarypress1_2_4am(rs.getString("tertiarypress1_2_4am"));
							data.setTertiarypress1_2_parameters(rs.getString("tertiarypress1_2_parameters"));
							data.setTertiarypress1_3_freq(rs.getString("tertiarypress1_3_freq"));
							data.setTertiarypress1_3_8am(rs.getString("tertiarypress1_3_8am"));
							data.setTertiarypress1_3_12pm(rs.getString("tertiarypress1_3_12pm"));
							data.setTertiarypress1_3_4pm(rs.getString("tertiarypress1_3_4pm"));
							data.setTertiarypress1_3_8pm(rs.getString("tertiarypress1_3_8pm"));
							data.setTertiarypress1_3_12am(rs.getString("tertiarypress1_3_12am"));
							data.setTertiarypress1_3_4am(rs.getString("tertiarypress1_3_4am"));
							data.setTertiarypress1_3_parameters(rs.getString("tertiarypress1_3_parameters"));
							data.setTertiarypress1_4_freq(rs.getString("tertiarypress1_4_freq"));
							data.setTertiarypress1_4_8am(rs.getString("tertiarypress1_4_8am"));
							data.setTertiarypress1_4_12pm(rs.getString("tertiarypress1_4_12pm"));
							data.setTertiarypress1_4_4pm(rs.getString("tertiarypress1_4_4pm"));
							data.setTertiarypress1_4_8pm(rs.getString("tertiarypress1_4_8pm"));
							data.setTertiarypress1_4_12am(rs.getString("tertiarypress1_4_12am"));
							data.setTertiarypress1_4_4am(rs.getString("tertiarypress1_4_4am"));
							data.setTertiarypress1_4_parameters(rs.getString("tertiarypress1_4_parameters"));
							data.setTertiarypress1_5_freq(rs.getString("tertiarypress1_5_freq"));
							data.setTertiarypress1_5_8am(rs.getString("tertiarypress1_5_8am"));
							data.setTertiarypress1_5_12pm(rs.getString("tertiarypress1_5_12pm"));
							data.setTertiarypress1_5_4pm(rs.getString("tertiarypress1_5_4pm"));
							data.setTertiarypress1_5_8pm(rs.getString("tertiarypress1_5_8pm"));
							data.setTertiarypress1_5_12am(rs.getString("tertiarypress1_5_12am"));
							data.setTertiarypress1_5_4am(rs.getString("tertiarypress1_5_4am"));
							data.setTertiarypress1_5_parameters(rs.getString("tertiarypress1_5_parameters"));
							data.setTertiarypress1_6_freq(rs.getString("tertiarypress1_6_freq"));
							data.setTertiarypress1_6_8am(rs.getString("tertiarypress1_6_8am"));
							data.setTertiarypress1_6_12pm(rs.getString("tertiarypress1_6_12pm"));
							data.setTertiarypress1_6_4pm(rs.getString("tertiarypress1_6_4pm"));
							data.setTertiarypress1_6_8pm(rs.getString("tertiarypress1_6_8pm"));
							data.setTertiarypress1_6_12am(rs.getString("tertiarypress1_6_12am"));
							data.setTertiarypress1_6_4am(rs.getString("tertiarypress1_6_4am"));
							data.setTertiarypress1_6_parameters(rs.getString("tertiarypress1_6_parameters"));
							data.setTertiarypress1_7_freq(rs.getString("tertiarypress1_7_freq"));
							data.setTertiarypress1_7_8am(rs.getString("tertiarypress1_7_8am"));
							data.setTertiarypress1_7_12pm(rs.getString("tertiarypress1_7_12pm"));
							data.setTertiarypress1_7_4pm(rs.getString("tertiarypress1_7_4pm"));
							data.setTertiarypress1_7_8pm(rs.getString("tertiarypress1_7_8pm"));
							data.setTertiarypress1_7_12am(rs.getString("tertiarypress1_7_12am"));
							data.setTertiarypress1_7_4am(rs.getString("tertiarypress1_7_4am"));
							data.setTertiarypress1_7_parameters(rs.getString("tertiarypress1_7_parameters"));
							data.setTertiarypress1_8_freq(rs.getString("tertiarypress1_8_freq"));
							data.setTertiarypress1_8_8am(rs.getString("tertiarypress1_8_8am"));
							data.setTertiarypress1_8_12pm(rs.getString("tertiarypress1_8_12pm"));
							data.setTertiarypress1_8_4pm(rs.getString("tertiarypress1_8_4pm"));
							data.setTertiarypress1_8_8pm(rs.getString("tertiarypress1_8_8pm"));
							data.setTertiarypress1_8_12am(rs.getString("tertiarypress1_8_12am"));
							data.setTertiarypress1_8_4am(rs.getString("tertiarypress1_8_4am"));
							data.setTertiarypress1_8_parameters(rs.getString("tertiarypress1_8_parameters"));
							data.setTertiarypress1_9_freq(rs.getString("tertiarypress1_9_freq"));
							data.setTertiarypress1_9_8am(rs.getString("tertiarypress1_9_8am"));
							data.setTertiarypress1_9_12pm(rs.getString("tertiarypress1_9_12pm"));
							data.setTertiarypress1_9_4pm(rs.getString("tertiarypress1_9_4pm"));
							data.setTertiarypress1_9_8pm(rs.getString("tertiarypress1_9_8pm"));
							data.setTertiarypress1_9_12am(rs.getString("tertiarypress1_9_12am"));
							data.setTertiarypress1_9_4am(rs.getString("tertiarypress1_9_4am"));
							data.setTertiarypress1_9_parameters(rs.getString("tertiarypress1_9_parameters"));
							data.setTertiarypress1_10_freq(rs.getString("tertiarypress1_10_freq"));
							data.setTertiarypress1_10_8am(rs.getString("tertiarypress1_10_8am"));
							data.setTertiarypress1_10_12pm(rs.getString("tertiarypress1_10_12pm"));
							data.setTertiarypress1_10_4pm(rs.getString("tertiarypress1_10_4pm"));
							data.setTertiarypress1_10_8pm(rs.getString("tertiarypress1_10_8pm"));
							data.setTertiarypress1_10_12am(rs.getString("tertiarypress1_10_12am"));
							data.setTertiarypress1_10_4am(rs.getString("tertiarypress1_10_4am"));
							data.setTertiarypress1_10_parameters(rs.getString("tertiarypress1_10_parameters"));
							data.setTertiarypress1_11_freq(rs.getString("tertiarypress1_11_freq"));
							data.setTertiarypress1_11_8am(rs.getString("tertiarypress1_11_8am"));
							data.setTertiarypress1_11_12pm(rs.getString("tertiarypress1_11_12pm"));
							data.setTertiarypress1_11_4pm(rs.getString("tertiarypress1_11_4pm"));
							data.setTertiarypress1_11_8pm(rs.getString("tertiarypress1_11_8pm"));
							data.setTertiarypress1_11_12am(rs.getString("tertiarypress1_11_12am"));
							data.setTertiarypress1_11_4am(rs.getString("tertiarypress1_11_4am"));
							data.setTertiarypress1_11_parameters(rs.getString("tertiarypress1_11_parameters"));
							data.setTertiarypress1_12_freq(rs.getString("tertiarypress1_12_freq"));
							data.setTertiarypress1_12_8am(rs.getString("tertiarypress1_12_8am"));
							data.setTertiarypress1_12_12pm(rs.getString("tertiarypress1_12_12pm"));
							data.setTertiarypress1_12_4pm(rs.getString("tertiarypress1_12_4pm"));
							data.setTertiarypress1_12_8pm(rs.getString("tertiarypress1_12_8pm"));
							data.setTertiarypress1_12_12am(rs.getString("tertiarypress1_12_12am"));
							data.setTertiarypress1_12_4am(rs.getString("tertiarypress1_12_4am"));
							data.setTertiarypress1_12_parameters(rs.getString("tertiarypress1_12_parameters"));
							data.setTertiarypress1_13_freq(rs.getString("tertiarypress1_13_freq"));
							data.setTertiarypress1_13_8am(rs.getString("tertiarypress1_13_8am"));
							data.setTertiarypress1_13_12pm(rs.getString("tertiarypress1_13_12pm"));
							data.setTertiarypress1_13_4pm(rs.getString("tertiarypress1_13_4pm"));
							data.setTertiarypress1_13_8pm(rs.getString("tertiarypress1_13_8pm"));
							data.setTertiarypress1_13_12am(rs.getString("tertiarypress1_13_12am"));
							data.setTertiarypress1_13_4am(rs.getString("tertiarypress1_13_4am"));
							data.setTertiarypress1_13_parameters(rs.getString("tertiarypress1_13_parameters"));
							data.setTertiarypress1_14_freq(rs.getString("tertiarypress1_14_freq"));
							data.setTertiarypress1_14_8am(rs.getString("tertiarypress1_14_8am"));
							data.setTertiarypress1_14_12pm(rs.getString("tertiarypress1_14_12pm"));
							data.setTertiarypress1_14_4pm(rs.getString("tertiarypress1_14_4pm"));
							data.setTertiarypress1_14_8pm(rs.getString("tertiarypress1_14_8pm"));
							data.setTertiarypress1_14_12am(rs.getString("tertiarypress1_14_12am"));
							data.setTertiarypress1_14_4am(rs.getString("tertiarypress1_14_4am"));
							data.setTertiarypress1_14_parameters(rs.getString("tertiarypress1_14_parameters"));
							data.setTertiarypress2_1_freq(rs.getString("tertiarypress2_1_freq"));
							data.setTertiarypress2_1_8am(rs.getString("tertiarypress2_1_8am"));
							data.setTertiarypress2_1_12pm(rs.getString("tertiarypress2_1_12pm"));
							data.setTertiarypress2_1_4pm(rs.getString("tertiarypress2_1_4pm"));
							data.setTertiarypress2_1_8pm(rs.getString("tertiarypress2_1_8pm"));
							data.setTertiarypress2_1_12am(rs.getString("tertiarypress2_1_12am"));
							data.setTertiarypress2_1_4am(rs.getString("tertiarypress2_1_4am"));
							data.setTertiarypress2_1_parameters(rs.getString("tertiarypress2_1_parameters"));
							data.setTertiarypress2_2_freq(rs.getString("tertiarypress2_2_freq"));
							data.setTertiarypress2_2_8am(rs.getString("tertiarypress2_2_8am"));
							data.setTertiarypress2_2_12pm(rs.getString("tertiarypress2_2_12pm"));
							data.setTertiarypress2_2_4pm(rs.getString("tertiarypress2_2_4pm"));
							data.setTertiarypress2_2_8pm(rs.getString("tertiarypress2_2_8pm"));
							data.setTertiarypress2_2_12am(rs.getString("tertiarypress2_2_12am"));
							data.setTertiarypress2_2_4am(rs.getString("tertiarypress2_2_4am"));
							data.setTertiarypress2_2_parameters(rs.getString("tertiarypress2_2_parameters"));
							data.setTertiarypress2_3_freq(rs.getString("tertiarypress2_3_freq"));
							data.setTertiarypress2_3_8am(rs.getString("tertiarypress2_3_8am"));
							data.setTertiarypress2_3_12pm(rs.getString("tertiarypress2_3_12pm"));
							data.setTertiarypress2_3_4pm(rs.getString("tertiarypress2_3_4pm"));
							data.setTertiarypress2_3_8pm(rs.getString("tertiarypress2_3_8pm"));
							data.setTertiarypress2_3_12am(rs.getString("tertiarypress2_3_12am"));
							data.setTertiarypress2_3_4am(rs.getString("tertiarypress2_3_4am"));
							data.setTertiarypress2_3_parameters(rs.getString("tertiarypress2_3_parameters"));
							data.setTertiarypress2_4_freq(rs.getString("tertiarypress2_4_freq"));
							data.setTertiarypress2_4_8am(rs.getString("tertiarypress2_4_8am"));
							data.setTertiarypress2_4_12pm(rs.getString("tertiarypress2_4_12pm"));
							data.setTertiarypress2_4_4pm(rs.getString("tertiarypress2_4_4pm"));
							data.setTertiarypress2_4_8pm(rs.getString("tertiarypress2_4_8pm"));
							data.setTertiarypress2_4_12am(rs.getString("tertiarypress2_4_12am"));
							data.setTertiarypress2_4_4am(rs.getString("tertiarypress2_4_4am"));
							data.setTertiarypress2_4_parameters(rs.getString("tertiarypress2_4_parameters"));
							data.setTertiarypress2_5_freq(rs.getString("tertiarypress2_5_freq"));
							data.setTertiarypress2_5_8am(rs.getString("tertiarypress2_5_8am"));
							data.setTertiarypress2_5_12pm(rs.getString("tertiarypress2_5_12pm"));
							data.setTertiarypress2_5_4pm(rs.getString("tertiarypress2_5_4pm"));
							data.setTertiarypress2_5_8pm(rs.getString("tertiarypress2_5_8pm"));
							data.setTertiarypress2_5_12am(rs.getString("tertiarypress2_5_12am"));
							data.setTertiarypress2_5_4am(rs.getString("tertiarypress2_5_4am"));
							data.setTertiarypress2_5_parameters(rs.getString("tertiarypress2_5_parameters"));
							data.setTertiarypress2_6_freq(rs.getString("tertiarypress2_6_freq"));
							data.setTertiarypress2_6_8am(rs.getString("tertiarypress2_6_8am"));
							data.setTertiarypress2_6_12pm(rs.getString("tertiarypress2_6_12pm"));
							data.setTertiarypress2_6_4pm(rs.getString("tertiarypress2_6_4pm"));
							data.setTertiarypress2_6_8pm(rs.getString("tertiarypress2_6_8pm"));
							data.setTertiarypress2_6_12am(rs.getString("tertiarypress2_6_12am"));
							data.setTertiarypress2_6_4am(rs.getString("tertiarypress2_6_4am"));
							data.setTertiarypress2_6_parameters(rs.getString("tertiarypress2_6_parameters"));
							data.setTertiarypress2_7_freq(rs.getString("tertiarypress2_7_freq"));
							data.setTertiarypress2_7_8am(rs.getString("tertiarypress2_7_8am"));
							data.setTertiarypress2_7_12pm(rs.getString("tertiarypress2_7_12pm"));
							data.setTertiarypress2_7_4pm(rs.getString("tertiarypress2_7_4pm"));
							data.setTertiarypress2_7_8pm(rs.getString("tertiarypress2_7_8pm"));
							data.setTertiarypress2_7_12am(rs.getString("tertiarypress2_7_12am"));
							data.setTertiarypress2_7_4am(rs.getString("tertiarypress2_7_4am"));
							data.setTertiarypress2_7_parameters(rs.getString("tertiarypress2_7_parameters"));
							data.setTertiarypress2_8_freq(rs.getString("tertiarypress2_8_freq"));
							data.setTertiarypress2_8_8am(rs.getString("tertiarypress2_8_8am"));
							data.setTertiarypress2_8_12pm(rs.getString("tertiarypress2_8_12pm"));
							data.setTertiarypress2_8_4pm(rs.getString("tertiarypress2_8_4pm"));
							data.setTertiarypress2_8_8pm(rs.getString("tertiarypress2_8_8pm"));
							data.setTertiarypress2_8_12am(rs.getString("tertiarypress2_8_12am"));
							data.setTertiarypress2_8_4am(rs.getString("tertiarypress2_8_4am"));
							data.setTertiarypress2_8_parameters(rs.getString("tertiarypress2_8_parameters"));
							data.setTertiarypress2_9_freq(rs.getString("tertiarypress2_9_freq"));
							data.setTertiarypress2_9_8am(rs.getString("tertiarypress2_9_8am"));
							data.setTertiarypress2_9_12pm(rs.getString("tertiarypress2_9_12pm"));
							data.setTertiarypress2_9_4pm(rs.getString("tertiarypress2_9_4pm"));
							data.setTertiarypress2_9_8pm(rs.getString("tertiarypress2_9_8pm"));
							data.setTertiarypress2_9_12am(rs.getString("tertiarypress2_9_12am"));
							data.setTertiarypress2_9_4am(rs.getString("tertiarypress2_9_4am"));
							data.setTertiarypress2_9_parameters(rs.getString("tertiarypress2_9_parameters"));
							data.setTertiarypress2_10_freq(rs.getString("tertiarypress2_10_freq"));
							data.setTertiarypress2_10_8am(rs.getString("tertiarypress2_10_8am"));
							data.setTertiarypress2_10_12pm(rs.getString("tertiarypress2_10_12pm"));
							data.setTertiarypress2_10_4pm(rs.getString("tertiarypress2_10_4pm"));
							data.setTertiarypress2_10_8pm(rs.getString("tertiarypress2_10_8pm"));
							data.setTertiarypress2_10_12am(rs.getString("tertiarypress2_10_12am"));
							data.setTertiarypress2_10_4am(rs.getString("tertiarypress2_10_4am"));
							data.setTertiarypress2_10_parameters(rs.getString("tertiarypress2_10_parameters"));
							data.setTertiarypress2_11_freq(rs.getString("tertiarypress2_11_freq"));
							data.setTertiarypress2_11_8am(rs.getString("tertiarypress2_11_8am"));
							data.setTertiarypress2_11_12pm(rs.getString("tertiarypress2_11_12pm"));
							data.setTertiarypress2_11_4pm(rs.getString("tertiarypress2_11_4pm"));
							data.setTertiarypress2_11_8pm(rs.getString("tertiarypress2_11_8pm"));
							data.setTertiarypress2_11_12am(rs.getString("tertiarypress2_11_12am"));
							data.setTertiarypress2_11_4am(rs.getString("tertiarypress2_11_4am"));
							data.setTertiarypress2_11_parameters(rs.getString("tertiarypress2_11_parameters"));
							data.setCutterlayboy_wetlap1_freq(rs.getString("cutterlayboy_wetlap1_freq"));
							data.setCutterlayboy_wetlap1_8am(rs.getString("cutterlayboy_wetlap1_8am"));
							data.setCutterlayboy_wetlap1_12pm(rs.getString("cutterlayboy_wetlap1_12pm"));
							data.setCutterlayboy_wetlap1_4pm(rs.getString("cutterlayboy_wetlap1_4pm"));
							data.setCutterlayboy_wetlap1_8pm(rs.getString("cutterlayboy_wetlap1_8pm"));
							data.setCutterlayboy_wetlap1_12am(rs.getString("cutterlayboy_wetlap1_12am"));
							data.setCutterlayboy_wetlap1_4am(rs.getString("cutterlayboy_wetlap1_4am"));
							data.setCutterlayboy_wetlap1_parameters(rs.getString("cutterlayboy_wetlap1_parameters"));
							data.setCutterlayboy_wetlap2_freq(rs.getString("cutterlayboy_wetlap2_freq"));
							data.setCutterlayboy_wetlap2_8am(rs.getString("cutterlayboy_wetlap2_8am"));
							data.setCutterlayboy_wetlap2_12pm(rs.getString("cutterlayboy_wetlap2_12pm"));
							data.setCutterlayboy_wetlap2_4pm(rs.getString("cutterlayboy_wetlap2_4pm"));
							data.setCutterlayboy_wetlap2_8pm(rs.getString("cutterlayboy_wetlap2_8pm"));
							data.setCutterlayboy_wetlap2_12am(rs.getString("cutterlayboy_wetlap2_12am"));
							data.setCutterlayboy_wetlap2_4am(rs.getString("cutterlayboy_wetlap2_4am"));
							data.setCutterlayboy_wetlap2_parameters(rs.getString("cutterlayboy_wetlap2_parameters"));
							data.setCutterlayboy_wetlap3_freq(rs.getString("cutterlayboy_wetlap3_freq"));
							data.setCutterlayboy_wetlap3_8am(rs.getString("cutterlayboy_wetlap3_8am"));
							data.setCutterlayboy_wetlap3_12pm(rs.getString("cutterlayboy_wetlap3_12pm"));
							data.setCutterlayboy_wetlap3_4pm(rs.getString("cutterlayboy_wetlap3_4pm"));
							data.setCutterlayboy_wetlap3_8pm(rs.getString("cutterlayboy_wetlap3_8pm"));
							data.setCutterlayboy_wetlap3_12am(rs.getString("cutterlayboy_wetlap3_12am"));
							data.setCutterlayboy_wetlap3_4am(rs.getString("cutterlayboy_wetlap3_4am"));
							data.setCutterlayboy_wetlap3_parameters(rs.getString("cutterlayboy_wetlap3_parameters"));
							data.setCutterlayboy_wetlap4_freq(rs.getString("cutterlayboy_wetlap4_freq"));
							data.setCutterlayboy_wetlap4_8am(rs.getString("cutterlayboy_wetlap4_8am"));
							data.setCutterlayboy_wetlap4_12pm(rs.getString("cutterlayboy_wetlap4_12pm"));
							data.setCutterlayboy_wetlap4_4pm(rs.getString("cutterlayboy_wetlap4_4pm"));
							data.setCutterlayboy_wetlap4_8pm(rs.getString("cutterlayboy_wetlap4_8pm"));
							data.setCutterlayboy_wetlap4_12am(rs.getString("cutterlayboy_wetlap4_12am"));
							data.setCutterlayboy_wetlap4_4am(rs.getString("cutterlayboy_wetlap4_4am"));
							data.setCutterlayboy_wetlap4_parameters(rs.getString("cutterlayboy_wetlap4_parameters"));
							data.setCutterlayboy_wetlap5_freq(rs.getString("cutterlayboy_wetlap5_freq"));
							data.setCutterlayboy_wetlap5_8am(rs.getString("cutterlayboy_wetlap5_8am"));
							data.setCutterlayboy_wetlap5_12pm(rs.getString("cutterlayboy_wetlap5_12pm"));
							data.setCutterlayboy_wetlap5_4pm(rs.getString("cutterlayboy_wetlap5_4pm"));
							data.setCutterlayboy_wetlap5_8pm(rs.getString("cutterlayboy_wetlap5_8pm"));
							data.setCutterlayboy_wetlap5_12am(rs.getString("cutterlayboy_wetlap5_12am"));
							data.setCutterlayboy_wetlap5_4am(rs.getString("cutterlayboy_wetlap5_4am"));
							data.setCutterlayboy_wetlap5_parameters(rs.getString("cutterlayboy_wetlap5_parameters"));
							data.setCutterlayboy_wetlap6_freq(rs.getString("cutterlayboy_wetlap6_freq"));
							data.setCutterlayboy_wetlap6_8am(rs.getString("cutterlayboy_wetlap6_8am"));
							data.setCutterlayboy_wetlap6_12pm(rs.getString("cutterlayboy_wetlap6_12pm"));
							data.setCutterlayboy_wetlap6_4pm(rs.getString("cutterlayboy_wetlap6_4pm"));
							data.setCutterlayboy_wetlap6_8pm(rs.getString("cutterlayboy_wetlap6_8pm"));
							data.setCutterlayboy_wetlap6_12am(rs.getString("cutterlayboy_wetlap6_12am"));
							data.setCutterlayboy_wetlap6_4am(rs.getString("cutterlayboy_wetlap6_4am"));
							data.setCutterlayboy_wetlap6_parameters(rs.getString("cutterlayboy_wetlap6_parameters"));
							data.setCutterlayboy_wetlap7_freq(rs.getString("cutterlayboy_wetlap7_freq"));
							data.setCutterlayboy_wetlap7_8am(rs.getString("cutterlayboy_wetlap7_8am"));
							data.setCutterlayboy_wetlap7_12pm(rs.getString("cutterlayboy_wetlap7_12pm"));
							data.setCutterlayboy_wetlap7_4pm(rs.getString("cutterlayboy_wetlap7_4pm"));
							data.setCutterlayboy_wetlap7_8pm(rs.getString("cutterlayboy_wetlap7_8pm"));
							data.setCutterlayboy_wetlap7_12am(rs.getString("cutterlayboy_wetlap7_12am"));
							data.setCutterlayboy_wetlap7_4am(rs.getString("cutterlayboy_wetlap7_4am"));
							data.setCutterlayboy_wetlap7_parameters(rs.getString("cutterlayboy_wetlap7_parameters"));
							
							data.setCmt9amarea(rs.getString("cmt9amarea"));
							data.setCmt1pmarea(rs.getString("cmt1pmarea"));
							data.setCmt5pmarea(rs.getString("cmt5pmarea"));
							data.setCmt9pmarea(rs.getString("cmt9pmarea"));
							data.setCmt1amarea(rs.getString("cmt1amarea"));
							data.setCmt5amarea(rs.getString("cmt5amarea"));
							data.setOk(rs.getString("ok"));
							data.setButton1pm(rs.getString("button1pm"));
							data.setButton5pm(rs.getString("button5pm"));
							data.setButton9pm(rs.getString("button9pm"));
							data.setButton1am(rs.getString("button1am"));
							data.setButton5am(rs.getString("button5am"));
							
							return data;
						}						
			});
		} catch (Exception e) {
			System.out.println(e.getMessage());
		}
		return oproute_2;
	}
	@Override
	public long getCountDatePercentage(String sdate,String edate) throws Exception {
		
		int _8am=0,_12pm=0,_4pm=0,_8pm=0,_12am=0,_4am=0;
		long _8ampercent=0, _12pmpercent=0,_4pmpercent=0,_8pmpercent=0,_12ampercent=0,_4ampercent=0;
	 	long percent=0;
		List<OpRoute_2> lst= getData(sdate,edate);
		for(OpRoute_2 data:lst)
		{
			if(data.getTertiarypress1_1_8am()!=null&&!data.getTertiarypress1_1_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_2_8am()!=null&&!data.getTertiarypress1_2_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_3_8am()!=null&&!data.getTertiarypress1_3_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_4_8am()!=null&&!data.getTertiarypress1_4_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_5_8am()!=null&&!data.getTertiarypress1_5_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_6_8am()!=null&&!data.getTertiarypress1_6_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_7_8am()!=null&&!data.getTertiarypress1_7_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_8_8am()!=null&&!data.getTertiarypress1_8_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_9_8am()!=null&&!data.getTertiarypress1_9_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_10_8am()!=null&&!data.getTertiarypress1_10_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_11_8am()!=null&&!data.getTertiarypress1_11_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_12_8am()!=null&&!data.getTertiarypress1_12_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_13_8am()!=null&&!data.getTertiarypress1_13_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_14_8am()!=null&&!data.getTertiarypress1_14_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_1_8am()!=null&&!data.getTertiarypress2_1_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_2_8am()!=null&&!data.getTertiarypress2_2_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_3_8am()!=null&&!data.getTertiarypress2_3_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_4_8am()!=null&&!data.getTertiarypress2_4_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_5_8am()!=null&&!data.getTertiarypress2_5_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_6_8am()!=null&&!data.getTertiarypress2_6_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_7_8am()!=null&&!data.getTertiarypress2_7_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_8_8am()!=null&&!data.getTertiarypress2_8_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_9_8am()!=null&&!data.getTertiarypress2_9_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_10_8am()!=null&&!data.getTertiarypress2_10_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_11_8am()!=null&&!data.getTertiarypress2_11_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap1_8am()!=null&&!data.getCutterlayboy_wetlap1_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap2_8am()!=null&&!data.getCutterlayboy_wetlap2_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap3_8am()!=null&&!data.getCutterlayboy_wetlap3_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap4_8am()!=null&&!data.getCutterlayboy_wetlap4_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap5_8am()!=null&&!data.getCutterlayboy_wetlap5_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap6_8am()!=null&&!data.getCutterlayboy_wetlap6_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap7_8am()!=null&&!data.getCutterlayboy_wetlap7_8am().equals("")){_8am++;}
			
			if(data.getTertiarypress1_1_12pm()!=null&&!data.getTertiarypress1_1_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_2_12pm()!=null&&!data.getTertiarypress1_2_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_3_12pm()!=null&&!data.getTertiarypress1_3_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_4_12pm()!=null&&!data.getTertiarypress1_4_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_5_12pm()!=null&&!data.getTertiarypress1_5_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_6_12pm()!=null&&!data.getTertiarypress1_6_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_7_12pm()!=null&&!data.getTertiarypress1_7_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_8_12pm()!=null&&!data.getTertiarypress1_8_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_9_12pm()!=null&&!data.getTertiarypress1_9_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_10_12pm()!=null&&!data.getTertiarypress1_10_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_11_12pm()!=null&&!data.getTertiarypress1_11_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_12_12pm()!=null&&!data.getTertiarypress1_12_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_13_12pm()!=null&&!data.getTertiarypress1_13_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_14_12pm()!=null&&!data.getTertiarypress1_14_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_1_12pm()!=null&&!data.getTertiarypress2_1_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_2_12pm()!=null&&!data.getTertiarypress2_2_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_3_12pm()!=null&&!data.getTertiarypress2_3_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_4_12pm()!=null&&!data.getTertiarypress2_4_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_5_12pm()!=null&&!data.getTertiarypress2_5_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_6_12pm()!=null&&!data.getTertiarypress2_6_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_7_12pm()!=null&&!data.getTertiarypress2_7_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_8_12pm()!=null&&!data.getTertiarypress2_8_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_9_12pm()!=null&&!data.getTertiarypress2_9_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_10_12pm()!=null&&!data.getTertiarypress2_10_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_11_12pm()!=null&&!data.getTertiarypress2_11_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap1_12pm()!=null&&!data.getCutterlayboy_wetlap1_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap2_12pm()!=null&&!data.getCutterlayboy_wetlap2_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap3_12pm()!=null&&!data.getCutterlayboy_wetlap3_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap4_12pm()!=null&&!data.getCutterlayboy_wetlap4_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap5_12pm()!=null&&!data.getCutterlayboy_wetlap5_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap6_12pm()!=null&&!data.getCutterlayboy_wetlap6_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap7_12pm()!=null&&!data.getCutterlayboy_wetlap7_12pm().equals("")){_12pm++;}

			
			if(data.getTertiarypress1_1_4pm()!=null&&!data.getTertiarypress1_1_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_2_4pm()!=null&&!data.getTertiarypress1_2_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_3_4pm()!=null&&!data.getTertiarypress1_3_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_4_4pm()!=null&&!data.getTertiarypress1_4_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_5_4pm()!=null&&!data.getTertiarypress1_5_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_6_4pm()!=null&&!data.getTertiarypress1_6_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_7_4pm()!=null&&!data.getTertiarypress1_7_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_8_4pm()!=null&&!data.getTertiarypress1_8_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_9_4pm()!=null&&!data.getTertiarypress1_9_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_10_4pm()!=null&&!data.getTertiarypress1_10_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_11_4pm()!=null&&!data.getTertiarypress1_11_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_12_4pm()!=null&&!data.getTertiarypress1_12_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_13_4pm()!=null&&!data.getTertiarypress1_13_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_14_4pm()!=null&&!data.getTertiarypress1_14_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_1_4pm()!=null&&!data.getTertiarypress2_1_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_2_4pm()!=null&&!data.getTertiarypress2_2_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_3_4pm()!=null&&!data.getTertiarypress2_3_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_4_4pm()!=null&&!data.getTertiarypress2_4_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_5_4pm()!=null&&!data.getTertiarypress2_5_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_6_4pm()!=null&&!data.getTertiarypress2_6_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_7_4pm()!=null&&!data.getTertiarypress2_7_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_8_4pm()!=null&&!data.getTertiarypress2_8_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_9_4pm()!=null&&!data.getTertiarypress2_9_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_10_4pm()!=null&&!data.getTertiarypress2_10_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_11_4pm()!=null&&!data.getTertiarypress2_11_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap1_4pm()!=null&&!data.getCutterlayboy_wetlap1_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap2_4pm()!=null&&!data.getCutterlayboy_wetlap2_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap3_4pm()!=null&&!data.getCutterlayboy_wetlap3_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap4_4pm()!=null&&!data.getCutterlayboy_wetlap4_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap5_4pm()!=null&&!data.getCutterlayboy_wetlap5_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap6_4pm()!=null&&!data.getCutterlayboy_wetlap6_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap7_4pm()!=null&&!data.getCutterlayboy_wetlap7_4pm().equals("")){_4pm++;}

			if(data.getTertiarypress1_1_8pm()!=null&&!data.getTertiarypress1_1_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_2_8pm()!=null&&!data.getTertiarypress1_2_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_3_8pm()!=null&&!data.getTertiarypress1_3_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_4_8pm()!=null&&!data.getTertiarypress1_4_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_5_8pm()!=null&&!data.getTertiarypress1_5_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_6_8pm()!=null&&!data.getTertiarypress1_6_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_7_8pm()!=null&&!data.getTertiarypress1_7_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_8_8pm()!=null&&!data.getTertiarypress1_8_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_9_8pm()!=null&&!data.getTertiarypress1_9_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_10_8pm()!=null&&!data.getTertiarypress1_10_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_11_8pm()!=null&&!data.getTertiarypress1_11_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_12_8pm()!=null&&!data.getTertiarypress1_12_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_13_8pm()!=null&&!data.getTertiarypress1_13_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_14_8pm()!=null&&!data.getTertiarypress1_14_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_1_8pm()!=null&&!data.getTertiarypress2_1_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_2_8pm()!=null&&!data.getTertiarypress2_2_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_3_8pm()!=null&&!data.getTertiarypress2_3_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_4_8pm()!=null&&!data.getTertiarypress2_4_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_5_8pm()!=null&&!data.getTertiarypress2_5_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_6_8pm()!=null&&!data.getTertiarypress2_6_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_7_8pm()!=null&&!data.getTertiarypress2_7_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_8_8pm()!=null&&!data.getTertiarypress2_8_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_9_8pm()!=null&&!data.getTertiarypress2_9_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_10_8pm()!=null&&!data.getTertiarypress2_10_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_11_8pm()!=null&&!data.getTertiarypress2_11_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap1_8pm()!=null&&!data.getCutterlayboy_wetlap1_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap2_8pm()!=null&&!data.getCutterlayboy_wetlap2_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap3_8pm()!=null&&!data.getCutterlayboy_wetlap3_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap4_8pm()!=null&&!data.getCutterlayboy_wetlap4_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap5_8pm()!=null&&!data.getCutterlayboy_wetlap5_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap6_8pm()!=null&&!data.getCutterlayboy_wetlap6_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap7_8pm()!=null&&!data.getCutterlayboy_wetlap7_8pm().equals("")){_8pm++;}

			if(data.getTertiarypress1_1_12am()!=null&&!data.getTertiarypress1_1_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_2_12am()!=null&&!data.getTertiarypress1_2_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_3_12am()!=null&&!data.getTertiarypress1_3_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_4_12am()!=null&&!data.getTertiarypress1_4_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_5_12am()!=null&&!data.getTertiarypress1_5_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_6_12am()!=null&&!data.getTertiarypress1_6_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_7_12am()!=null&&!data.getTertiarypress1_7_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_8_12am()!=null&&!data.getTertiarypress1_8_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_9_12am()!=null&&!data.getTertiarypress1_9_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_10_12am()!=null&&!data.getTertiarypress1_10_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_11_12am()!=null&&!data.getTertiarypress1_11_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_12_12am()!=null&&!data.getTertiarypress1_12_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_13_12am()!=null&&!data.getTertiarypress1_13_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_14_12am()!=null&&!data.getTertiarypress1_14_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_1_12am()!=null&&!data.getTertiarypress2_1_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_2_12am()!=null&&!data.getTertiarypress2_2_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_3_12am()!=null&&!data.getTertiarypress2_3_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_4_12am()!=null&&!data.getTertiarypress2_4_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_5_12am()!=null&&!data.getTertiarypress2_5_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_6_12am()!=null&&!data.getTertiarypress2_6_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_7_12am()!=null&&!data.getTertiarypress2_7_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_8_12am()!=null&&!data.getTertiarypress2_8_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_9_12am()!=null&&!data.getTertiarypress2_9_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_10_12am()!=null&&!data.getTertiarypress2_10_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_11_12am()!=null&&!data.getTertiarypress2_11_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap1_12am()!=null&&!data.getCutterlayboy_wetlap1_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap2_12am()!=null&&!data.getCutterlayboy_wetlap2_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap3_12am()!=null&&!data.getCutterlayboy_wetlap3_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap4_12am()!=null&&!data.getCutterlayboy_wetlap4_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap5_12am()!=null&&!data.getCutterlayboy_wetlap5_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap6_12am()!=null&&!data.getCutterlayboy_wetlap6_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap7_12am()!=null&&!data.getCutterlayboy_wetlap7_12am().equals("")){_12am++;}

			if(data.getTertiarypress1_1_4am()!=null&&!data.getTertiarypress1_1_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_2_4am()!=null&&!data.getTertiarypress1_2_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_3_4am()!=null&&!data.getTertiarypress1_3_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_4_4am()!=null&&!data.getTertiarypress1_4_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_5_4am()!=null&&!data.getTertiarypress1_5_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_6_4am()!=null&&!data.getTertiarypress1_6_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_7_4am()!=null&&!data.getTertiarypress1_7_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_8_4am()!=null&&!data.getTertiarypress1_8_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_9_4am()!=null&&!data.getTertiarypress1_9_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_10_4am()!=null&&!data.getTertiarypress1_10_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_11_4am()!=null&&!data.getTertiarypress1_11_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_12_4am()!=null&&!data.getTertiarypress1_12_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_13_4am()!=null&&!data.getTertiarypress1_13_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_14_4am()!=null&&!data.getTertiarypress1_14_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_1_4am()!=null&&!data.getTertiarypress2_1_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_2_4am()!=null&&!data.getTertiarypress2_2_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_3_4am()!=null&&!data.getTertiarypress2_3_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_4_4am()!=null&&!data.getTertiarypress2_4_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_5_4am()!=null&&!data.getTertiarypress2_5_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_6_4am()!=null&&!data.getTertiarypress2_6_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_7_4am()!=null&&!data.getTertiarypress2_7_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_8_4am()!=null&&!data.getTertiarypress2_8_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_9_4am()!=null&&!data.getTertiarypress2_9_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_10_4am()!=null&&!data.getTertiarypress2_10_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_11_4am()!=null&&!data.getTertiarypress2_11_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap1_4am()!=null&&!data.getCutterlayboy_wetlap1_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap2_4am()!=null&&!data.getCutterlayboy_wetlap2_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap3_4am()!=null&&!data.getCutterlayboy_wetlap3_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap4_4am()!=null&&!data.getCutterlayboy_wetlap4_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap5_4am()!=null&&!data.getCutterlayboy_wetlap5_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap6_4am()!=null&&!data.getCutterlayboy_wetlap6_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap7_4am()!=null&&!data.getCutterlayboy_wetlap7_4am().equals("")){_4am++;}
			
			if(_8am>=5){_8ampercent=100;}
			if(_12pm>=5){_12pmpercent=100;}
			if(_4pm>=5){_4pmpercent=100;}
			if(_8pm>=5){_8pmpercent=100;}
			if(_12am>=5){_12ampercent=100;}
			if(_4am>=5){_4ampercent=100;}
			if(data.getCmt9amarea()!=null&&!data.getCmt9amarea().equals(""))
			{_8ampercent=100;}
			if(data.getCmt1pmarea()!=null&&!data.getCmt1pmarea().equals(""))
			{_12pmpercent=100;}				
			if(data.getCmt5pmarea()!=null&&!data.getCmt5pmarea().equals(""))
			{_4pmpercent=100;}
			if(data.getCmt9pmarea()!=null&&!data.getCmt9pmarea().equals(""))
			{_8pmpercent=100;}
			if(data.getCmt1amarea()!=null&&!data.getCmt1amarea().equals(""))
			{_12ampercent=100;}
			if(data.getCmt5amarea()!=null&&!data.getCmt5amarea().equals(""))
			{_4ampercent=100;}
			 percent=(_8ampercent+_12pmpercent+_4pmpercent+_8pmpercent+_12ampercent+_4ampercent)/6;
		}
		return percent;
	}
	@Override
	public List<Integer> getCount(String sdate,String edate) throws Exception {
		
		int count=0, _8am=0,_12pm=0,_4pm=0,_8pm=0,_12am=0,_4am=0;
		List<OpRoute_2> lst= getData(sdate,edate);
		List<Integer> al=new ArrayList<Integer>();
		for(OpRoute_2 data:lst)
		{
			if(data.getTertiarypress1_1_8am()!=null&&!data.getTertiarypress1_1_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_2_8am()!=null&&!data.getTertiarypress1_2_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_3_8am()!=null&&!data.getTertiarypress1_3_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_4_8am()!=null&&!data.getTertiarypress1_4_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_5_8am()!=null&&!data.getTertiarypress1_5_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_6_8am()!=null&&!data.getTertiarypress1_6_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_7_8am()!=null&&!data.getTertiarypress1_7_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_8_8am()!=null&&!data.getTertiarypress1_8_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_9_8am()!=null&&!data.getTertiarypress1_9_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_10_8am()!=null&&!data.getTertiarypress1_10_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_11_8am()!=null&&!data.getTertiarypress1_11_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_12_8am()!=null&&!data.getTertiarypress1_12_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_13_8am()!=null&&!data.getTertiarypress1_13_8am().equals("")){_8am++;}
			if(data.getTertiarypress1_14_8am()!=null&&!data.getTertiarypress1_14_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_1_8am()!=null&&!data.getTertiarypress2_1_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_2_8am()!=null&&!data.getTertiarypress2_2_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_3_8am()!=null&&!data.getTertiarypress2_3_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_4_8am()!=null&&!data.getTertiarypress2_4_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_5_8am()!=null&&!data.getTertiarypress2_5_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_6_8am()!=null&&!data.getTertiarypress2_6_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_7_8am()!=null&&!data.getTertiarypress2_7_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_8_8am()!=null&&!data.getTertiarypress2_8_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_9_8am()!=null&&!data.getTertiarypress2_9_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_10_8am()!=null&&!data.getTertiarypress2_10_8am().equals("")){_8am++;}
			if(data.getTertiarypress2_11_8am()!=null&&!data.getTertiarypress2_11_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap1_8am()!=null&&!data.getCutterlayboy_wetlap1_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap2_8am()!=null&&!data.getCutterlayboy_wetlap2_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap3_8am()!=null&&!data.getCutterlayboy_wetlap3_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap4_8am()!=null&&!data.getCutterlayboy_wetlap4_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap5_8am()!=null&&!data.getCutterlayboy_wetlap5_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap6_8am()!=null&&!data.getCutterlayboy_wetlap6_8am().equals("")){_8am++;}
			if(data.getCutterlayboy_wetlap7_8am()!=null&&!data.getCutterlayboy_wetlap7_8am().equals("")){_8am++;}
			
			if(data.getTertiarypress1_1_12pm()!=null&&!data.getTertiarypress1_1_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_2_12pm()!=null&&!data.getTertiarypress1_2_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_3_12pm()!=null&&!data.getTertiarypress1_3_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_4_12pm()!=null&&!data.getTertiarypress1_4_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_5_12pm()!=null&&!data.getTertiarypress1_5_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_6_12pm()!=null&&!data.getTertiarypress1_6_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_7_12pm()!=null&&!data.getTertiarypress1_7_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_8_12pm()!=null&&!data.getTertiarypress1_8_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_9_12pm()!=null&&!data.getTertiarypress1_9_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_10_12pm()!=null&&!data.getTertiarypress1_10_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_11_12pm()!=null&&!data.getTertiarypress1_11_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_12_12pm()!=null&&!data.getTertiarypress1_12_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_13_12pm()!=null&&!data.getTertiarypress1_13_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress1_14_12pm()!=null&&!data.getTertiarypress1_14_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_1_12pm()!=null&&!data.getTertiarypress2_1_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_2_12pm()!=null&&!data.getTertiarypress2_2_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_3_12pm()!=null&&!data.getTertiarypress2_3_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_4_12pm()!=null&&!data.getTertiarypress2_4_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_5_12pm()!=null&&!data.getTertiarypress2_5_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_6_12pm()!=null&&!data.getTertiarypress2_6_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_7_12pm()!=null&&!data.getTertiarypress2_7_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_8_12pm()!=null&&!data.getTertiarypress2_8_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_9_12pm()!=null&&!data.getTertiarypress2_9_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_10_12pm()!=null&&!data.getTertiarypress2_10_12pm().equals("")){_12pm++;}
			if(data.getTertiarypress2_11_12pm()!=null&&!data.getTertiarypress2_11_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap1_12pm()!=null&&!data.getCutterlayboy_wetlap1_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap2_12pm()!=null&&!data.getCutterlayboy_wetlap2_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap3_12pm()!=null&&!data.getCutterlayboy_wetlap3_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap4_12pm()!=null&&!data.getCutterlayboy_wetlap4_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap5_12pm()!=null&&!data.getCutterlayboy_wetlap5_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap6_12pm()!=null&&!data.getCutterlayboy_wetlap6_12pm().equals("")){_12pm++;}
			if(data.getCutterlayboy_wetlap7_12pm()!=null&&!data.getCutterlayboy_wetlap7_12pm().equals("")){_12pm++;}

			
			if(data.getTertiarypress1_1_4pm()!=null&&!data.getTertiarypress1_1_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_2_4pm()!=null&&!data.getTertiarypress1_2_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_3_4pm()!=null&&!data.getTertiarypress1_3_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_4_4pm()!=null&&!data.getTertiarypress1_4_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_5_4pm()!=null&&!data.getTertiarypress1_5_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_6_4pm()!=null&&!data.getTertiarypress1_6_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_7_4pm()!=null&&!data.getTertiarypress1_7_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_8_4pm()!=null&&!data.getTertiarypress1_8_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_9_4pm()!=null&&!data.getTertiarypress1_9_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_10_4pm()!=null&&!data.getTertiarypress1_10_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_11_4pm()!=null&&!data.getTertiarypress1_11_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_12_4pm()!=null&&!data.getTertiarypress1_12_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_13_4pm()!=null&&!data.getTertiarypress1_13_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress1_14_4pm()!=null&&!data.getTertiarypress1_14_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_1_4pm()!=null&&!data.getTertiarypress2_1_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_2_4pm()!=null&&!data.getTertiarypress2_2_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_3_4pm()!=null&&!data.getTertiarypress2_3_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_4_4pm()!=null&&!data.getTertiarypress2_4_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_5_4pm()!=null&&!data.getTertiarypress2_5_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_6_4pm()!=null&&!data.getTertiarypress2_6_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_7_4pm()!=null&&!data.getTertiarypress2_7_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_8_4pm()!=null&&!data.getTertiarypress2_8_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_9_4pm()!=null&&!data.getTertiarypress2_9_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_10_4pm()!=null&&!data.getTertiarypress2_10_4pm().equals("")){_4pm++;}
			if(data.getTertiarypress2_11_4pm()!=null&&!data.getTertiarypress2_11_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap1_4pm()!=null&&!data.getCutterlayboy_wetlap1_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap2_4pm()!=null&&!data.getCutterlayboy_wetlap2_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap3_4pm()!=null&&!data.getCutterlayboy_wetlap3_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap4_4pm()!=null&&!data.getCutterlayboy_wetlap4_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap5_4pm()!=null&&!data.getCutterlayboy_wetlap5_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap6_4pm()!=null&&!data.getCutterlayboy_wetlap6_4pm().equals("")){_4pm++;}
			if(data.getCutterlayboy_wetlap7_4pm()!=null&&!data.getCutterlayboy_wetlap7_4pm().equals("")){_4pm++;}

			if(data.getTertiarypress1_1_8pm()!=null&&!data.getTertiarypress1_1_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_2_8pm()!=null&&!data.getTertiarypress1_2_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_3_8pm()!=null&&!data.getTertiarypress1_3_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_4_8pm()!=null&&!data.getTertiarypress1_4_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_5_8pm()!=null&&!data.getTertiarypress1_5_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_6_8pm()!=null&&!data.getTertiarypress1_6_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_7_8pm()!=null&&!data.getTertiarypress1_7_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_8_8pm()!=null&&!data.getTertiarypress1_8_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_9_8pm()!=null&&!data.getTertiarypress1_9_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_10_8pm()!=null&&!data.getTertiarypress1_10_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_11_8pm()!=null&&!data.getTertiarypress1_11_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_12_8pm()!=null&&!data.getTertiarypress1_12_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_13_8pm()!=null&&!data.getTertiarypress1_13_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress1_14_8pm()!=null&&!data.getTertiarypress1_14_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_1_8pm()!=null&&!data.getTertiarypress2_1_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_2_8pm()!=null&&!data.getTertiarypress2_2_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_3_8pm()!=null&&!data.getTertiarypress2_3_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_4_8pm()!=null&&!data.getTertiarypress2_4_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_5_8pm()!=null&&!data.getTertiarypress2_5_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_6_8pm()!=null&&!data.getTertiarypress2_6_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_7_8pm()!=null&&!data.getTertiarypress2_7_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_8_8pm()!=null&&!data.getTertiarypress2_8_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_9_8pm()!=null&&!data.getTertiarypress2_9_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_10_8pm()!=null&&!data.getTertiarypress2_10_8pm().equals("")){_8pm++;}
			if(data.getTertiarypress2_11_8pm()!=null&&!data.getTertiarypress2_11_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap1_8pm()!=null&&!data.getCutterlayboy_wetlap1_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap2_8pm()!=null&&!data.getCutterlayboy_wetlap2_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap3_8pm()!=null&&!data.getCutterlayboy_wetlap3_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap4_8pm()!=null&&!data.getCutterlayboy_wetlap4_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap5_8pm()!=null&&!data.getCutterlayboy_wetlap5_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap6_8pm()!=null&&!data.getCutterlayboy_wetlap6_8pm().equals("")){_8pm++;}
			if(data.getCutterlayboy_wetlap7_8pm()!=null&&!data.getCutterlayboy_wetlap7_8pm().equals("")){_8pm++;}

			if(data.getTertiarypress1_1_12am()!=null&&!data.getTertiarypress1_1_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_2_12am()!=null&&!data.getTertiarypress1_2_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_3_12am()!=null&&!data.getTertiarypress1_3_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_4_12am()!=null&&!data.getTertiarypress1_4_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_5_12am()!=null&&!data.getTertiarypress1_5_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_6_12am()!=null&&!data.getTertiarypress1_6_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_7_12am()!=null&&!data.getTertiarypress1_7_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_8_12am()!=null&&!data.getTertiarypress1_8_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_9_12am()!=null&&!data.getTertiarypress1_9_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_10_12am()!=null&&!data.getTertiarypress1_10_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_11_12am()!=null&&!data.getTertiarypress1_11_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_12_12am()!=null&&!data.getTertiarypress1_12_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_13_12am()!=null&&!data.getTertiarypress1_13_12am().equals("")){_12am++;}
			if(data.getTertiarypress1_14_12am()!=null&&!data.getTertiarypress1_14_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_1_12am()!=null&&!data.getTertiarypress2_1_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_2_12am()!=null&&!data.getTertiarypress2_2_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_3_12am()!=null&&!data.getTertiarypress2_3_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_4_12am()!=null&&!data.getTertiarypress2_4_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_5_12am()!=null&&!data.getTertiarypress2_5_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_6_12am()!=null&&!data.getTertiarypress2_6_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_7_12am()!=null&&!data.getTertiarypress2_7_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_8_12am()!=null&&!data.getTertiarypress2_8_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_9_12am()!=null&&!data.getTertiarypress2_9_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_10_12am()!=null&&!data.getTertiarypress2_10_12am().equals("")){_12am++;}
			if(data.getTertiarypress2_11_12am()!=null&&!data.getTertiarypress2_11_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap1_12am()!=null&&!data.getCutterlayboy_wetlap1_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap2_12am()!=null&&!data.getCutterlayboy_wetlap2_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap3_12am()!=null&&!data.getCutterlayboy_wetlap3_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap4_12am()!=null&&!data.getCutterlayboy_wetlap4_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap5_12am()!=null&&!data.getCutterlayboy_wetlap5_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap6_12am()!=null&&!data.getCutterlayboy_wetlap6_12am().equals("")){_12am++;}
			if(data.getCutterlayboy_wetlap7_12am()!=null&&!data.getCutterlayboy_wetlap7_12am().equals("")){_12am++;}

			if(data.getTertiarypress1_1_4am()!=null&&!data.getTertiarypress1_1_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_2_4am()!=null&&!data.getTertiarypress1_2_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_3_4am()!=null&&!data.getTertiarypress1_3_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_4_4am()!=null&&!data.getTertiarypress1_4_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_5_4am()!=null&&!data.getTertiarypress1_5_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_6_4am()!=null&&!data.getTertiarypress1_6_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_7_4am()!=null&&!data.getTertiarypress1_7_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_8_4am()!=null&&!data.getTertiarypress1_8_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_9_4am()!=null&&!data.getTertiarypress1_9_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_10_4am()!=null&&!data.getTertiarypress1_10_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_11_4am()!=null&&!data.getTertiarypress1_11_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_12_4am()!=null&&!data.getTertiarypress1_12_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_13_4am()!=null&&!data.getTertiarypress1_13_4am().equals("")){_4am++;}
			if(data.getTertiarypress1_14_4am()!=null&&!data.getTertiarypress1_14_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_1_4am()!=null&&!data.getTertiarypress2_1_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_2_4am()!=null&&!data.getTertiarypress2_2_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_3_4am()!=null&&!data.getTertiarypress2_3_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_4_4am()!=null&&!data.getTertiarypress2_4_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_5_4am()!=null&&!data.getTertiarypress2_5_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_6_4am()!=null&&!data.getTertiarypress2_6_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_7_4am()!=null&&!data.getTertiarypress2_7_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_8_4am()!=null&&!data.getTertiarypress2_8_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_9_4am()!=null&&!data.getTertiarypress2_9_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_10_4am()!=null&&!data.getTertiarypress2_10_4am().equals("")){_4am++;}
			if(data.getTertiarypress2_11_4am()!=null&&!data.getTertiarypress2_11_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap1_4am()!=null&&!data.getCutterlayboy_wetlap1_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap2_4am()!=null&&!data.getCutterlayboy_wetlap2_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap3_4am()!=null&&!data.getCutterlayboy_wetlap3_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap4_4am()!=null&&!data.getCutterlayboy_wetlap4_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap5_4am()!=null&&!data.getCutterlayboy_wetlap5_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap6_4am()!=null&&!data.getCutterlayboy_wetlap6_4am().equals("")){_4am++;}
			if(data.getCutterlayboy_wetlap7_4am()!=null&&!data.getCutterlayboy_wetlap7_4am().equals("")){_4am++;}
			
			if(_8am>=3){count++;}
			if(_12pm>=3){count++;}
			if(_4pm>=3){count++;}
			if(_8pm>=3){count++;}
			if(_12am>=3){count++;}
			if(_4am>=3){count++;}
			al.add(count);
			_8am=0;_12pm=0;_4pm=0;_8pm=0;_12am=0;_4am=0;
			count=0;
		}
		return al;
	}
}
