INSERT INTO   [R1Operator_pm5]  ( position
           ,operatorname
           ,date
           ,crew
           ,shift
           ,machinedown
           ,leadInRollcol1
           ,leadInRollcol2
           ,leadInRollcol3
           ,leadInRollcol4
           ,leadInRollcol5
           ,leadInRollcol1Desc
           ,leadInRollcol2Desc
           ,leadInRollcol3Desc
           ,leadInRollcol4Desc
           ,leadInRollcol5Desc
           ,sectionRollcol1
           ,sectionRollcol1Desc
           ,breakassemblycol1
           ,breakassemblycol2
           ,breakassemblycol1Desc
           ,breakassemblycol2Desc
           ,slitterscol1
           ,slitterscol2
           ,slitterscol3
           ,slitterscol1Desc
           ,slitterscol2Desc
           ,slitterscol3Desc
           ,trimassemblycol1
           ,trimassemblycol2
           ,trimassemblycol3
           ,trimassemblycol4
           ,trimassemblycol1Desc
           ,trimassemblycol2Desc
           ,trimassemblycol3Desc
           ,trimassemblycol4Desc
           ,tensiionRollcol1
           ,tensiionRollcol2
           ,tensiionRollcol3
           ,tensiionRollcol1Desc
           ,tensiionRollcol2Desc
           ,tensiionRollcol3Desc
           ,winderDrum1col1
           ,winderDrum1col2
           ,winderDrum1col3
           ,winderDrum1col4
           ,winderDrum1col5
           ,winderDrum1col1Desc
           ,winderDrum1col2Desc
           ,winderDrum1col3Desc
           ,winderDrum1col4Desc
           ,winderDrum1col5Desc
           ,winderDrum2col1
           ,winderDrum2col2
           ,winderDrum2col3
           ,winderDrum2col4
           ,winderDrum2col5
           ,winderDrum2col1Desc
           ,winderDrum2col2Desc
           ,winderDrum2col3Desc
           ,winderDrum2col4Desc
           ,winderDrum2col5Desc
           ,rollEjectorcol1
           ,rollEjectorcol2
           ,rollEjectorcol3
           ,rollEjectorcol1Desc
           ,rollEjectorcol2Desc
           ,rollEjectorcol3Desc
           ,riderRollcol1
           ,riderRollcol2
           ,riderRollcol3
           ,riderRollcol4
           ,riderRollcol5
           ,riderRollcol6
           ,riderRollcol7
           ,riderRollcol8
           ,riderRollcol1Desc
           ,riderRollcol2Desc
           ,riderRollcol3Desc
           ,riderRollcol4Desc
           ,riderRollcol5Desc
           ,riderRollcol6Desc
           ,riderRollcol7Desc
           ,riderRollcol8Desc
           ,bowedRollcol1
           ,bowedRollcol2
           ,bowedRollcol3
           ,bowedRollcol1Desc
           ,bowedRollcol2Desc
           ,bowedRollcol3Desc
           ,coreChuckscol1
           ,coreChuckscol2
           ,coreChuckscol3
           ,coreChuckscol4
           ,coreChuckscol1Desc
           ,coreChuckscol2Desc
           ,coreChuckscol3Desc
           ,coreChuckscol4Desc
           ,nipGuardcol1
           ,nipGuardcol2
           ,nipGuardcol3
           ,nipGuardcol1Desc
           ,nipGuardcol2Desc
           ,nipGuardcol3Desc
           ,tableleftgatecol1
           ,tableleftgatecol2
           ,tableleftgatecol1Desc
           ,tableleftgatecol2Desc)
     VALUES
           (
        :position,
		:operatorname,
		:date,
		:crew,
		:shift,
		:machinedown,
		:leadInRollcol1,
		:leadInRollcol2,
		:leadInRollcol3,
		:leadInRollcol4,
		:leadInRollcol5,
		:leadInRollcol1Desc,
		:leadInRollcol2Desc,
		:leadInRollcol3Desc,
		:leadInRollcol4Desc,
		:leadInRollcol5Desc,
		:sectionRollcol1,
		:sectionRollcol1Desc,
		:breakassemblycol1,
		:breakassemblycol2,
		:breakassemblycol1Desc,
		:breakassemblycol2Desc,
		:slitterscol1,
		:slitterscol2,
		:slitterscol3,
		:slitterscol1Desc,
		:slitterscol2Desc,
		:slitterscol3Desc,
		:trimassemblycol1,
		:trimassemblycol2,
		:trimassemblycol3,
		:trimassemblycol4,
		:trimassemblycol1Desc,
		:trimassemblycol2Desc,
		:trimassemblycol3Desc,
		:trimassemblycol4Desc,
		:tensiionRollcol1,
		:tensiionRollcol2,
		:tensiionRollcol3,
		:tensiionRollcol1Desc,
		:tensiionRollcol2Desc,
		:tensiionRollcol3Desc,
		:winderDrum1col1,
		:winderDrum1col2,
		:winderDrum1col3,
		:winderDrum1col4,
		:winderDrum1col5,
		:winderDrum1col1Desc,
		:winderDrum1col2Desc,
		:winderDrum1col3Desc,
		:winderDrum1col4Desc,
		:winderDrum1col5Desc,
		:winderDrum2col1,
		:winderDrum2col2,
		:winderDrum2col3,
		:winderDrum2col4,
		:winderDrum2col5,
		:winderDrum2col1Desc,
		:winderDrum2col2Desc,
		:winderDrum2col3Desc,
		:winderDrum2col4Desc,
		:winderDrum2col5Desc,
		:rollEjectorcol1,
		:rollEjectorcol2,
		:rollEjectorcol3,
		:rollEjectorcol1Desc,
		:rollEjectorcol2Desc,
		:rollEjectorcol3Desc,
		:riderRollcol1,
		:riderRollcol2,
		:riderRollcol3,
		:riderRollcol4,
		:riderRollcol5,
		:riderRollcol6,
		:riderRollcol7,
		:riderRollcol8,
		:riderRollcol1Desc,
		:riderRollcol2Desc,
		:riderRollcol3Desc,
		:riderRollcol4Desc,
		:riderRollcol5Desc,
		:riderRollcol6Desc,
		:riderRollcol7Desc,
		:riderRollcol8Desc,
		:bowedRollcol1,
		:bowedRollcol2,
		:bowedRollcol3,
		:bowedRollcol1Desc,
		:bowedRollcol2Desc,
		:bowedRollcol3Desc,
		:coreChuckscol1,
		:coreChuckscol2,
		:coreChuckscol3,
		:coreChuckscol4,
		:coreChuckscol1Desc,
		:coreChuckscol2Desc,
		:coreChuckscol3Desc,
		:coreChuckscol4Desc,
		:nipGuardcol1,
		:nipGuardcol2,
		:nipGuardcol3,
		:nipGuardcol1Desc,
		:nipGuardcol2Desc,
		:nipGuardcol3Desc,
		:tableleftgatecol1,
		:tableleftgatecol2,
		:tableleftgatecol1Desc,
		:tableleftgatecol2Desc
		)
 

