INSERT INTO [R1Operator]
           ([position]
           ,[operator_name]
           ,[date]
           ,[crew]
           ,[shift]
		   ,[machinedown]
           ,[lead_In_Roll_col1]
           ,[lead_In_Roll_col2]
           ,[lead_In_Roll_col3]
           ,[lead_In_Roll_col4]
           ,[lead_In_Roll_col5]
           ,[lead_In_Roll_col1_Desc]
           ,[lead_In_Roll_col2_Desc]
           ,[lead_In_Roll_col3_Desc]
           ,[lead_In_Roll_col4_Desc]
           ,[lead_In_Roll_col5_Desc]
           ,[section_Roll_col1]
           ,[section_Roll_col1_Desc]
           ,[break_assembly_col1]
           ,[break_assembly_col2]
           ,[break_assembly_col1_Desc]
           ,[break_assembly_col2_Desc]
           ,[slitters_col1]
           ,[slitters_col2]
           ,[slitters_col3]
           ,[slitters_col1_Desc]
           ,[slitters_col2_Desc]
           ,[slitters_col3_Desc]
           ,[trim_assembly_col1]
           ,[trim_assembly_col2]
           ,[trim_assembly_col3]
           ,[trim_assembly_col4]
           ,[trim_assembly_col1_Desc]
           ,[trim_assembly_col2_Desc]
           ,[trim_assembly_col3_Desc]
           ,[trim_assembly_col4_Desc]
           ,[tensiion_Roll_col1]
           ,[tensiion_Roll_col2]
           ,[tensiion_Roll_col3]
           ,[tensiion_Roll_col1_Desc]
           ,[tensiion_Roll_col2_Desc]
           ,[tensiion_Roll_col3_Desc]
           ,[winder_Drum_col1]
           ,[winder_Drum_col2]
           ,[winder_Drum_col3]
           ,[winder_Drum_col4]
           ,[winder_Drum_col5]
           ,[winder_Drum_col1_Desc]
           ,[winder_Drum_col2_Desc]
           ,[winder_Drum_col3_Desc]
           ,[winder_Drum_col4_Desc]
           ,[winder_Drum_col5_Desc]
           ,[winder_Drum2_col1]
           ,[winder_Drum2_col2]
           ,[winder_Drum2_col3]
           ,[winder_Drum2_col4]
           ,[winder_Drum2_col5]
           ,[winder_Drum2_col1_Desc]
           ,[winder_Drum2_col2_Desc]
           ,[winder_Drum2_col3_Desc]
           ,[winder_Drum2_col4_Desc]
           ,[winder_Drum2_col5_Desc]
           ,[roll_Ejector_Col1]
           ,[roll_Ejector_Col2]
           ,[roll_Ejector_Col3]
           ,[roll_Ejector_Col1_Desc]
           ,[roll_Ejector_Col2_Desc]
           ,[roll_Ejector_Col3_Desc]
           ,[rider_Roll_Col1]
           ,[rider_Roll_Col2]
           ,[rider_Roll_Col3]
           ,[rider_Roll_Col4]
           ,[rider_Roll_Col5]
           ,[rider_Roll_Col6]
           ,[rider_Roll_Col7]
           ,[rider_Roll_Col8]
           ,[rider_Roll_Col1_Desc]
           ,[rider_Roll_Col2_Desc]
           ,[rider_Roll_Col3_Desc]
           ,[rider_Roll_Col4_Desc]
           ,[rider_Roll_Col5_Desc]
           ,[rider_Roll_Col6_Desc]
           ,[rider_Roll_Col7_Desc]
           ,[rider_Roll_Col8_Desc]
           ,[bowed_Roll_Col1]
           ,[bowed_Roll_Col2]
           ,[bowed_Roll_Col3]
           ,[bowed_Roll_Col1_Desc]
           ,[bowed_Roll_Col2_Desc]
           ,[bowed_Roll_Col3_Desc]
           ,[core_Chucks_col1]
           ,[core_Chucks_col2]
           ,[core_Chucks_col3]
           ,[core_Chucks_col4]
           ,[core_Chucks_col1_Desc]
           ,[core_Chucks_col2_Desc]
           ,[core_Chucks_col3_Desc]
           ,[core_Chucks_col4_Desc]
           ,[nip_Guard_col1]
           ,[nip_Guard_col2]
           ,[nip_Guard_col3]
           ,[nip_Guard_col1_Desc]
           ,[nip_Guard_col2_Desc]
           ,[nip_Guard_col3_Desc]
           ,[table_left_gate_col1]
           ,[table_left_gate_col2]
           ,[table_left_gate_col1_Desc]
           ,[table_left_gate_col2_Desc])
     VALUES
           (
        :position,
		:operatorName,
		:edate,
		:crew,
		:shift,
		:machinedown,
		:leadInRollCol1,
		:leadInRollCol2,
		:leadInRollCol3,
		:leadInRollCol4,
		:leadInRollCol5,
		:leadInRollCol1Desc,
		:leadInRollCol2Desc,
		:leadInRollCol3Desc,
		:leadInRollCol4Desc,
		:leadInRollCol5Desc,
		:sectionRollCol1,
		:sectionRollCol1Desc,
		:breakAssemblyCol1,
		:breakAssemblyCol2,
		:breakAssemblyCol1Desc,
		:breakAssemblyCol2Desc,
		:slittersCol1,
		:slittersCol2,
		:slittersCol3,
		:slittersCol1Desc,
		:slittersCol2Desc,
		:slittersCol3Desc,
		:trimAssemblyCol1,
		:trimAssemblyCol2,
		:trimAssemblyCol3,
		:trimAssemblyCol4,
		:trimAssemblyCol1Desc,
		:trimAssemblyCol2Desc,
		:trimAssemblyCol3Desc,
		:trimAssemblyCol4Desc,
		:tensiionRollCol1,
		:tensiionRollCol2,
		:tensiionRollCol3,
		:tensiionRollCol1Desc,
		:tensiionRollCol2Desc,
		:tensiionRollCol3Desc,
		:winderDrum1Col1,
		:winderDrum1Col2,
		:winderDrum1Col3,
		:winderDrum1Col4,
		:winderDrum1Col5,
		:winderDrum1Col1Desc,
		:winderDrum1Col2Desc,
		:winderDrum1Col3Desc,
		:winderDrum1Col4Desc,
		:winderDrum1Col5Desc,
		:winderDrum2Col1,
		:winderDrum2Col2,
		:winderDrum2Col3,
		:winderDrum2Col4,
		:winderDrum2Col5,
		:winderDrum2Col1Desc,
		:winderDrum2Col2Desc,
		:winderDrum2Col3Desc,
		:winderDrum2Col4Desc,
		:winderDrum2Col5Desc,
		:rollEjectorCol1,
		:rollEjectorCol2,
		:rollEjectorCol3,
		:rollEjectorCol1Desc,
		:rollEjectorCol2Desc,
		:rollEjectorCol3Desc,
		:riderRollCol1,
		:riderRollCol2,
		:riderRollCol3,
		:riderRollCol4,
		:riderRollCol5,
		:riderRollCol6,
		:riderRollCol7,
		:riderRollCol8,
		:riderRollCol1Desc,
		:riderRollCol2Desc,
		:riderRollCol3Desc,
		:riderRollCol4Desc,
		:riderRollCol5Desc,
		:riderRollCol6Desc,
		:riderRollCol7Desc,
		:riderRollCol8Desc,
		:bowedRollCol1,
		:bowedRollCol2,
		:bowedRollCol3,
		:bowedRollCol1Desc,
		:bowedRollCol2Desc,
		:bowedRollCol3Desc,
		:coreChucksCol1,
		:coreChucksCol2,
		:coreChucksCol3,
		:coreChucksCol4,
		:coreChucksCol1Desc,
		:coreChucksCol2Desc,
		:coreChucksCol3Desc,
		:coreChucksCol4Desc,
		:nipGuardCol1,
		:nipGuardCol2,
		:nipGuardCol3,
		:nipGuardCol1Desc,
		:nipGuardCol2Desc,
		:nipGuardCol3Desc,
		:tableLeftGateCol1,
		:tableLeftGateCol2,
		:tableLeftGateCol1Desc,
		:tableLeftGateCol2Desc
		)
 

