UPDATE [machineTender]
   SET [position] = :position,
      [operator_name] = :operatorName,
      [date] = :edate,
      [crew] = :crew,
      [shift] = :shift,
      [forming_Section_col1] = :formingSectionCol1,
      [forming_Section_col2] = :formingSectionCol2,
      [forming_Section_col3] = :formingSectionCol3,
      [forming_Section_col4] = :formingSectionCol4,
      [forming_Section_col5] = :formingSectionCol5,
      [forming_Section_col6] = :formingSectionCol6,
      [forming_Section_col7] = :formingSectionCol7,
      [forming_Section_col8] = :formingSectionCol8,
      [forming_Section_col9] = :formingSectionCol9,
      [forming_Section_col10] = :formingSectionCol10,
      [forming_Section_col11] = :formingSectionCol11,
      [forming_Section_col12] = :formingSectionCol12,
      [forming_Section_col13] = :formingSectionCol13,
      [forming_Section_col14] = :formingSectionCol14,
      [forming_Section_col1_Desc] = :formingSectionCol1Desc,
      [forming_Section_col2_Desc] =:formingSectionCol2Desc,
      [forming_Section_col3_Desc] = :formingSectionCol3Desc,
      [forming_Section_col4_Desc] = :formingSectionCol4Desc,
      [forming_Section_col5_Desc] = :formingSectionCol5Desc,
      [forming_Section_col6_Desc] = :formingSectionCol6Desc,
      [forming_Section_col7_Desc] = :formingSectionCol7Desc,
      [forming_Section_col8_Desc] = :formingSectionCol8Desc,
      [forming_Section_col9_Desc] = :formingSectionCol9Desc,
      [forming_Section_col10_Desc] = :formingSectionCol10Desc,
      [forming_Section_col11_Desc] = :formingSectionCol11Desc,
      [forming_Section_col12_Desc] = :formingSectionCol12Desc,
      [forming_Section_col13_Desc] = :formingSectionCol13Desc,
      [forming_Section_col14_Desc] = :formingSectionCol14Desc,
      [suction_pressure_Roll_col1] = :suctionPressureRollCol1,
      [suction_pressure_Roll_col2] = :suctionPressureRollCol2,
      [suction_pressure_Roll_col3] = :suctionPressureRollCol3,
      [suction_pressure_Roll_col4] = :suctionPressureRollCol4,
      [suction_pressure_Roll_col5] = :suctionPressureRollCol5,
      [suction_pressure_Roll_col6] = :suctionPressureRollCol6,
      [suction_pressure_Roll_col7] = :suctionPressureRollCol7,
      [suction_pressure_Roll_col1_Desc] = :suctionPressureRollCol1Desc,
      [suction_pressure_Roll_col2_Desc] = :suctionPressureRollCol2Desc,
      [suction_pressure_Roll_col3_Desc] = :suctionPressureRollCol3Desc,
      [suction_pressure_Roll_col4_Desc] = :suctionPressureRollCol4Desc,
      [suction_pressure_Roll_col5_Desc] = :suctionPressureRollCol5Desc,
      [suction_pressure_Roll_col6_Desc] = :suctionPressureRollCol6Desc,
      [suction_pressure_Roll_col7_Desc] = :suctionPressureRollCol7Desc,
      [yankee_Dryer_col1] = :yankeeDryerCol1,
      [yankee_Dryer_col2] = :yankeeDryerCol2,
      [yankee_Dryer_col3] = :yankeeDryerCol3,
      [yankee_Dryer_col4] = :yankeeDryerCol4,
      [yankee_Dryer_col5] = :yankeeDryerCol5,
      [yankee_Dryer_col1_Desc] = :yankeeDryerCol1Desc,
      [yankee_Dryer_col2_Desc] = :yankeeDryerCol2Desc,
      [yankee_Dryer_col3_Desc] = :yankeeDryerCol3Desc,
      [yankee_Dryer_col4_Desc] = :yankeeDryerCol4Desc,
      [yankee_Dryer_col5_Desc] = :yankeeDryerCol5Desc,
      [drive_Roll_col1] = :driveRollCol1,
      [drive_Roll_col2] = :driveRollCol2,
      [drive_Roll_col3] = :driveRollCol3,
      [drive_Roll_col4] = :driveRollCol4,
      [drive_Roll_col5] = :driveRollCol5,
      [drive_Roll_col6] = :driveRollCol6,
      [drive_Roll_col7] = :driveRollCol7,
      [drive_Roll_col1_Desc] = :driveRollCol1Desc,
      [drive_Roll_col2_Desc] = :driveRollCol2Desc,
      [drive_Roll_col3_Desc] = :driveRollCol3Desc,
      [drive_Roll_col4_Desc] = :driveRollCol4Desc,
      [drive_Roll_col5_Desc] = :driveRollCol5Desc,
      [drive_Roll_col6_Desc] = :driveRollCol6Desc,
      [drive_Roll_col7_Desc] = :driveRollCol7Desc,
      [press_Section_col1] = :pressSectionCol1,
      [press_Section_col2] = :pressSectionCol2,
      [press_Section_col3] = :pressSectionCol3,
      [press_Section_col4] = :pressSectionCol4,
      [press_Section_col5] = :pressSectionCol5,
      [press_Section_col6] = :pressSectionCol6,
      [press_Section_col7] = :pressSectionCol7,
      [press_Section_col8] = :pressSectionCol8,
      [press_Section_col1_Desc] = :pressSectionCol1Desc,
      [press_Section_col2_Desc] = :pressSectionCol2Desc,
      [press_Section_col3_Desc] = :pressSectionCol3Desc,
      [press_Section_col4_Desc] = :pressSectionCol4Desc,
      [press_Section_col5_Desc] = :pressSectionCol5Desc,
      [press_Section_col6_Desc] = :pressSectionCol6Desc,
      [press_Section_col7_Desc] = :pressSectionCol7Desc,
      [press_Section_col8_Desc] = :pressSectionCol8Desc,
      [upper_press_col1] = :upperPressCol1,
      [upper_press_col2] = :upperPressCol2,
      [upper_press_col3] = :upperPressCol3,
      [upper_press_col4] = :upperPressCol4,
      [upper_press_col5] = :upperPressCol5,
      [upper_press_col6] = :upperPressCol6,
      [upper_press_col7] = :upperPressCol7,
      [upper_press_col8] = :upperPressCol8,
      [upper_press_col9] = :upperPressCol9,
      [upper_press_col1_Desc] = :upperPressCol1Desc,
      [upper_press_col2_Desc] = :upperPressCol2Desc,
      [upper_press_col3_Desc] = :upperPressCol3Desc,
      [upper_press_col4_Desc] = :upperPressCol4Desc,
      [upper_press_col5_Desc] = :upperPressCol5Desc,
      [upper_press_col6_Desc] = :upperPressCol6Desc,
      [upper_press_col7_Desc] = :upperPressCol7Desc,
      [upper_press_col8_Desc] = :upperPressCol8Desc,
      [upper_press_col9_Desc] = :upperPressCol9Desc,
      [chemical_totes_col1] = :chemicalTotesCol1,
      [chemical_totes_col2] = :chemicalTotesCol2,
      [chemical_totes_col3] = :chemicalTotesCol3,
      [chemical_totes_col4] = :chemicalTotesCol4,
      [chemical_totes_col5] = :chemicalTotesCol5,
      [chemical_totes_col1_Desc] = :chemicalTotesCol1Desc,
      [chemical_totes_col2_Desc] = :chemicalTotesCol2Desc,
      [chemical_totes_col3_Desc] = :chemicalTotesCol3Desc,
      [chemical_totes_col4_Desc] = :chemicalTotesCol4Desc,
      [chemical_totes_col5_Desc] = :chemicalTotesCol5Desc,
      [fan_pump_col1] = :fanPumpCol1,
      [fan_pump_col2] = :fanPumpCol2,
      [fan_pump_col3_west] =:fanPumpCol3Inbound
      ,[fan_pump_col3_east] =:fanPumpCol3Outbound
      ,[fan_pump_col4_inbound] = :fanPumpCol4Inbound
      ,[fan_pump_col4_outbound] =:fanPumpCol4Outbound
      ,[fan_pump_col1_Desc] =:fanPumpCol1Desc
      ,[fan_pump_col2_Desc] =:fanPumpCol2Desc
      ,[fan_pump_col3_Desc] =:fanPumpCol3Desc
      ,[fan_pump_col4_Desc] =:fanPumpCol4Desc
      ,[selectifier_Screen_col1] =:selectifierScreenCol1
      ,[selectifier_Screen_col2] =:selectifierScreenCol2
      ,[selectifier_Screen_col3] =:selectifierScreenCol3
      ,[selectifier_Screen_col4_inbound] =:selectifierScreenCol4Inbound
      ,[selectifier_Screen_col4_outbound] =:selectifierScreenCol4Outbound
      ,[selectifier_Screen_col5] =:selectifierScreenCol5
      ,[selectifier_Screen_col6_inbound] =:selectifierScreenCol6Inbound
      ,[selectifier_Screen_col6_outbound] =:selectifierScreenCol6Outbound
      ,[selectifier_Screen_col7] =:selectifierScreenCol7
      ,[selectifier_Screen_col8] =:selectifierScreenCol8
      ,[selectifier_Screen_col9_inbound] =:selectifierScreenCol9Inbound
      ,[selectifier_Screen_col9_outbound] =:selectifierScreenCol9Outbound
      ,[selectifier_Screen_col10] =:selectifierScreenCol10
      ,[selectifier_Screen_col11_inbound] =:selectifierScreenCol11Inbound
      ,[selectifier_Screen_col11_outbound] =:selectifierScreenCol11Outbound
      ,[selectifier_Screen_col1_Desc] =:selectifierScreenCol1Desc
      ,[selectifier_Screen_col2_Desc] =:selectifierScreenCol2Desc
      ,[selectifier_Screen_col3_Desc] =:selectifierScreenCol3Desc
      ,[selectifier_Screen_col4_Desc] =:selectifierScreenCol4Desc
      ,[selectifier_Screen_col5_Desc] =:selectifierScreenCol5Desc
      ,[selectifier_Screen_col6_Desc] =:selectifierScreenCol6Desc
      ,[selectifier_Screen_col7_Desc] =:selectifierScreenCol7Desc
      ,[selectifier_Screen_col8_Desc] =:selectifierScreenCol8Desc
      ,[selectifier_Screen_col9_Desc] =:selectifierScreenCol9Desc
      ,[selectifier_Screen_col10_Desc] =:selectifierScreenCol10Desc
      ,[selectifier_Screen_col11_Desc] =:selectifierScreenCol11Desc
      ,[vacume_pump_col1] =:vacumePumpCol1
      ,[vacume_pump_col2] =:vacumePumpCol2
      ,[vacume_pump_col3] =:vacumePumpCol3
      ,[vacume_pump_col4_inbound] = :vacumePumpCol4Inbound
      ,[vacume_pump_col4_outbound] = :vacumePumpCol4Outbound
      ,[vacume_pump_col5_inbound] = :vacumePumpCol5Inbound
      ,[vacume_pump_col5_outbound] = :vacumePumpCol5Outbound
      ,[vacume_pump_col6] = :vacumePumpCol6
      ,[vacume_pump_col7_inbound] = :vacumePumpCol7Inbound
      ,[vacume_pump_col7_outbound] = :vacumePumpCol7Outbound
      ,[vacume_pump_col8] = :vacumePumpCol8
      ,[vacume_pump_col9] = :vacumePumpCol9
      ,[vacume_pump_col10] = :vacumePumpCol10
      ,[vacume_pump_col11] = :vacumePumpCol11
      ,[vacume_pump_col12] = :vacumePumpCol12
      ,[vacume_pump_col13] = :vacumePumpCol13
      ,[vacume_pump_col14] = :vacumePumpCol14
      ,[vacume_pump_col15_inbound] = :vacumePumpCol15Inbound
      ,[vacume_pump_col15_outbound] =:vacumePumpCol15Outbound
      ,[vacume_pump_col16] = :vacumePumpCol16
      ,[vacume_pump_col17] = :vacumePumpCol17
      ,[vacume_pump_col18] = :vacumePumpCol18
      ,[vacume_pump_col19] = :vacumePumpCol19
      ,[vacume_pump_col20] = :vacumePumpCol20
      ,[vacume_pump_col21] = :vacumePumpCol21
      ,[vacume_pump_col22] = :vacumePumpCol22
      ,[vacume_pump_col23] = :vacumePumpCol23
      ,[vacume_pump_col24] = :vacumePumpCol24
      ,[vacume_pump_col25] = :vacumePumpCol25
      ,[vacume_pump_col26] = :vacumePumpCol26
      ,[vacume_pump_col27] = :vacumePumpCol27
      ,[vacume_pump_col28] = :vacumePumpCol28
      ,[vacume_pump_col29] = :vacumePumpCol29
      ,[vacume_pump_col30] = :vacumePumpCol30
      ,[vacume_pump_col31] = :vacumePumpCol31
      ,[vacume_pump_col32] = :vacumePumpCol32
      ,[vacume_pump_col33] = :vacumePumpCol33
      ,[vacume_pump_col34] = :vacumePumpCol34
      ,[vacume_pump_col35] = :vacumePumpCol35
      ,[vacume_pump_col36] = :vacumePumpCol36
      ,[vacume_pump_col1_Desc] = :vacumePumpCol1Desc
      ,[vacume_pump_col2_Desc] = :vacumePumpCol2Desc
      ,[vacume_pump_col3_Desc] = :vacumePumpCol3Desc
      ,[vacume_pump_col4_Desc] = :vacumePumpCol4Desc
      ,[vacume_pump_col5_Desc] = :vacumePumpCol5Desc
      ,[vacume_pump_col6_Desc] = :vacumePumpCol6Desc
      ,[vacume_pump_col7_Desc] = :vacumePumpCol7Desc
      ,[vacume_pump_col8_Desc] = :vacumePumpCol8Desc
      ,[vacume_pump_col9_Desc] = :vacumePumpCol9Desc
      ,[vacume_pump_col10_Desc] =:vacumePumpCol10Desc
      ,[vacume_pump_col11_Desc] =:vacumePumpCol11Desc
      ,[vacume_pump_col12_Desc] =:vacumePumpCol12Desc
      ,[vacume_pump_col13_Desc] =:vacumePumpCol13Desc
      ,[vacume_pump_col14_Desc] =:vacumePumpCol14Desc
      ,[vacume_pump_col15_Desc] =:vacumePumpCol15Desc
      ,[vacume_pump_col16_Desc] =:vacumePumpCol16Desc
      ,[vacume_pump_col17_Desc] =:vacumePumpCol17Desc
      ,[vacume_pump_col18_Desc] =:vacumePumpCol18Desc
      ,[vacume_pump_col19_Desc] =:vacumePumpCol19Desc
      ,[vacume_pump_col20_Desc] =:vacumePumpCol20Desc
      ,[vacume_pump_col21_Desc] =:vacumePumpCol21Desc
      ,[vacume_pump_col22_Desc] =:vacumePumpCol22Desc
      ,[vacume_pump_col23_Desc] =:vacumePumpCol23Desc
      ,[vacume_pump_col24_Desc] =:vacumePumpCol24Desc
      ,[vacume_pump_col25_Desc] =:vacumePumpCol25Desc
      ,[vacume_pump_col26_Desc] =:vacumePumpCol26Desc
      ,[vacume_pump_col27_Desc] =:vacumePumpCol27Desc
      ,[vacume_pump_col28_Desc] =:vacumePumpCol28Desc
      ,[vacume_pump_col29_Desc] =:vacumePumpCol29Desc
      ,[vacume_pump_col30_Desc] =:vacumePumpCol30Desc
      ,[vacume_pump_col31_Desc] =:vacumePumpCol31Desc
      ,[vacume_pump_col32_Desc] =:vacumePumpCol32Desc
      ,[vacume_pump_col33_Desc] =:vacumePumpCol33Desc
      ,[vacume_pump_col34_Desc] =:vacumePumpCol34Desc
      ,[vacume_pump_col35_Desc] =:vacumePumpCol35Desc
      ,[vacume_pump_col36_Desc] =:vacumePumpCol36Desc
      ,[river_water_col1] = :riverWaterCol1
      ,[river_water_col2] = :riverWaterCol2
      ,[river_water_col1Out] = :riverWaterCol1Out
      ,[river_water_col2Out] = :riverWaterCol2Out
      ,[river_water_col1_Desc] = :riverWaterCol1Desc
      ,[river_water_col2_Desc] = :riverWaterCol2Desc
      ,[showercol1] = :showercol1
      ,[showercol2North] = :showercol2North
      ,[showercol2South] = :showercol2South
      ,[showercol3] = :showercol3
      ,[showercol4North] =:showercol4North
      ,[showercol4South] =:showercol4South
      ,[showercol5] = :showercol5
      ,[showercol6North] =:showercol6North
      ,[showercol6South] =:showercol6South
      ,[showercol7] = :showercol7
      ,[showercol7Out] = :showercol7Out
      ,[showercol1Desc] =:showercol1Desc
      ,[showercol2Desc] =:showercol2Desc
      ,[showercol3Desc] =:showercol3Desc
      ,[showercol4Desc] =:showercol4Desc
      ,[showercol5Desc] =:showercol5Desc
      ,[showercol6Desc] =:showercol6Desc
      ,[showercol7Desc] =:showercol7Desc
      ,[fillupcentcol1] =:fillupcentcol1
      ,[fillupcentcol2] =:fillupcentcol2
      ,[fillupcentcol3] =:fillupcentcol3
      ,[fillupcentcol4] =:fillupcentcol4
      ,[fillupcentcol5] =:fillupcentcol5
      ,[fillupcentcol6] =:fillupcentcol6
      ,[fillupcentcol7] =:fillupcentcol7
      ,[fillupcentcol8] =:fillupcentcol8
      ,[fillupcentcol9] =:fillupcentcol9
      ,[fillupcentcol1Desc] =:fillupcentcol1Desc
      ,[fillupcentcol2Desc] =:fillupcentcol2Desc
      ,[fillupcentcol3Desc] =:fillupcentcol3Desc
      ,[fillupcentcol4Desc] =:fillupcentcol4Desc
      ,[fillupcentcol5Desc] =:fillupcentcol5Desc
      ,[fillupcentcol6Desc] =:fillupcentcol6Desc
      ,[fillupcentcol7Desc] =:fillupcentcol7Desc
      ,[fillupcentcol8Desc] =:fillupcentcol8Desc
      ,[fillupcentcol9Desc] =:fillupcentcol9Desc
      ,[checkairfilterforheadbox] =:checkairfilterforheadbox
      ,[checkairfilterforheadboxremark] =:checkairfilterforheadboxremark
      ,[driveRollCol8] =:driveRollCol8
	  ,[driveRollCol8Desc] =:driveRollCol8Desc
	  ,[blowwetendanddryendmotor] =:blowwetendanddryendmotor
	  ,[blowwetendanddryendmotorremark] =:blowwetendanddryendmotorremark
	  ,[checkheadboxaircompressorintelfiltercleanliness] =:checkheadboxaircompressorintelfiltercleanliness
	  ,[checkheadboxaircompressorintelfiltercleanlinessdesc] =:checkheadboxaircompressorintelfiltercleanlinessdesc
	  ,[headboxairfilterscleaning] =:headboxairfilterscleaning
	  ,[headboxairfilterscleaningdesc] =:headboxairfilterscleaningdesc
	  ,[rotatingShowers] =:rotatingShowers
      ,[rotatingShowersremark] =:rotatingShowersremark
      ,[rotationShowersValve] =:rotationShowersValve
      ,[rotationShowersValveremark] =:rotationShowersValveremark
 WHERE id=:id
 

